const pathToImage = "../assets/images/d2items/misc";

// Object Array of all the runes in the game
const miscItems = [
  {
    name: "Chipped Ruby",
    type: "Gem",
    image: `${pathToImage}/Chipped_Ruby.webp`,
    properties: [],
  },
  {
    name: "Chipped Emerald",
    type: "Gem",
    image: `${pathToImage}/Chipped_Emerald.webp`,
    properties: [],
  },
  {
    name: "Chipped Sapphire",
    type: "Gem",
    image: `${pathToImage}/Chipped_Sapphire.webp`,
    properties: [],
  },
  {
    name: "Chipped Topaz",
    type: "Gem",
    image: `${pathToImage}/Chipped_Topaz.webp`,
    properties: [],
  },
  {
    name: "Chipped Amethyst",
    type: "Gem",
    image: `${pathToImage}/Chipped_Amethyst.webp`,
    properties: [],
  },
  {
    name: "Chipped Diamond",
    type: "Gem",
    image: `${pathToImage}/Chipped_Diamond.webp`,
    properties: [],
  },
  {
    name: "Chipped Skull",
    type: "Gem",
    image: `${pathToImage}/Chipped_Skull.webp`,
    properties: [],
  },
  {
    name: "Flawed Ruby",
    type: "Gem",
    image: `${pathToImage}/Flawed_Ruby.webp`,
    properties: [],
  },
  {
    name: "Flawed Emerald",
    type: "Gem",
    image: `${pathToImage}/Flawed_Emerald.webp`,
    properties: [],
  },
  {
    name: "Flawed Sapphire",
    type: "Gem",
    image: `${pathToImage}/Flawed_Sapphire.webp`,
    properties: [],
  },
  {
    name: "Flawed Topaz",
    type: "Gem",
    image: `${pathToImage}/Flawed_Topaz.webp`,
    properties: [],
  },
  {
    name: "Flawed Amethyst",
    type: "Gem",
    image: `${pathToImage}/Flawed_Amethyst.webp`,
    properties: [],
  },
  {
    name: "Flawed Diamond",
    type: "Gem",
    image: `${pathToImage}/Flawed_Diamond.webp`,
    properties: [],
  },
  {
    name: "Flawed Skull",
    type: "Gem",
    image: `${pathToImage}/Flawed_Skull.webp`,
    properties: [],
  },
  {
    name: "Ruby",
    type: "Gem",
    image: `${pathToImage}/Ruby.webp`,
    properties: [],
  },
  {
    name: "Emerald",
    type: "Gem",
    image: `${pathToImage}/Emerald.webp`,
    properties: [],
  },
  {
    name: "Sapphire",
    type: "Gem",
    image: `${pathToImage}/Sapphire.webp`,
    properties: [],
  },
  {
    name: "Topaz",
    type: "Gem",
    image: `${pathToImage}/Topaz.webp`,
    properties: [],
  },
  {
    name: "Amethyst",
    type: "Gem",
    image: `${pathToImage}/Amethyst.webp`,
    properties: [],
  },
  {
    name: "Diamond",
    type: "Gem",
    image: `${pathToImage}/Diamond.webp`,
    properties: [],
  },
  {
    name: "Skull",
    type: "Gem",
    image: `${pathToImage}/Skull.webp`,
    properties: [],
  },
  {
    name: "Flawless Ruby",
    type: "Gem",
    image: `${pathToImage}/Flawless_Ruby.webp`,
    properties: [],
  },
  {
    name: "Flawless Emerald",
    type: "Gem",
    image: `${pathToImage}/Flawless_Emeral.webp`,
    properties: [],
  },
  {
    name: "Flawless Sapphire",
    type: "Gem",
    image: `${pathToImage}/Flawless_Sapphire.webp`,
    properties: [],
  },
  {
    name: "Flawless Topaz",
    type: "Gem",
    image: `${pathToImage}/Flawless_Topaz.webp`,
    properties: [],
  },
  {
    name: "Flawless Amethyst",
    type: "Gem",
    image: `${pathToImage}/Flawless_Amethyst.webp`,
    properties: [],
  },
  {
    name: "Flawless Diamond",
    type: "Gem",
    image: `${pathToImage}/Flawless_Diamond.webp`,
    properties: [],
  },
  {
    name: "Flawless Skull",
    type: "Gem",
    image: `${pathToImage}/Flawless_Skull.webp`,
    properties: [],
  },
  {
    name: "Perfect Ruby",
    type: "Gem",
    image: `${pathToImage}/Perfect_Ruby.webp`,
    properties: [],
  },
  {
    name: "Perfect Emerald",
    type: "Gem",
    image: `${pathToImage}/Perfect_Emerald.webp`,
    properties: [],
  },
  {
    name: "Perfect Sapphire",
    type: "Gem",
    image: `${pathToImage}/Perfect_Sapphire.webp`,
    properties: [],
  },
  {
    name: "Perfect Topaz",
    type: "Gem",
    image: `${pathToImage}/Perfect_Topaz.webp`,
    properties: [],
  },
  {
    name: "Perfect Amethyst",
    type: "Gem",
    image: `${pathToImage}/Perfect_Amethyst.webp`,
    properties: [],
  },
  {
    name: "Perfect Diamond",
    type: "Gem",
    image: `${pathToImage}/Perfect_Diamond.webp`,
    properties: [],
  },
  {
    name: "Perfect Skull",
    type: "Gem",
    image: `${pathToImage}/Perfect_Skull.webp`,
    properties: [],
  },
  {
    name: "Perfect Gems",
    type: "Gem",
    image: `${pathToImage}/Perfect_Gems.webp`,
    properties: [],
  },
  {
    name: "Full Rejuvenation",
    type: "Potion",
    image: `${pathToImage}/Full_Rejuv.webp`,
    properties: [],
  },
  {
    name: "Key of Destruction",
    type: "Misc",
    image: `${pathToImage}/Diablo2_Key.webp`,
    properties: [],
  },
  {
    name: "Key of Terror",
    type: "Misc",
    image: `${pathToImage}/Diablo2_Key.webp`,
    properties: [],
  },
  {
    name: "Key of Hate",
    type: "Misc",
    image: `${pathToImage}/Diablo2_Key.webp`,
    properties: [],
  },
  {
    name: "3x3 Keyset",
    type: "Misc",
    image: `${pathToImage}/3x3_Key_Set.webp`,
    properties: [],
  },
  {
    name: "Twisted Essence of Suffering",
    type: "Misc",
    image: `${pathToImage}/Essence_of_Suffering.webp`,
    properties: [],
  },
  {
    name: "Burning Essence of Terror",
    type: "Misc",
    image: `${pathToImage}/Essence_of_Terror.webp`,
    properties: [],
  },
  {
    name: "Charged Essence of Hatred",
    type: "Misc",
    image: `${pathToImage}/Essence_of_Hatred.webp`,
    properties: [],
  },
  {
    name: "Festering Essence of Destruction",
    type: "Misc",
    image: `${pathToImage}/Essence_of_Destruction.webp`,
    properties: [],
  },
  {
    name: "Token of Absolution",
    type: "Misc",
    image: `${pathToImage}/Token_of_Absolution.webp`,
    properties: [],
  },
];

export default miscItems;
