// const pathToImage = 'assets/images/d2items/misc';

// Object Array of all the runes in the game
const miscItems = [
    {
        "name": "Chipped Ruby",
        "type": "Gem",
        "image": "",
        "properties": [],
    },
    {
        "name": "Chipped Emerald",
        "type": "Gem",
        "image": "",
        "properties": [],
    },
    {
        "name": "Chipped Sapphire",
        "type": "Gem",
        "image": "",
        "properties": [],
    },
    {
        "name": "Chipped Topaz",
        "type": "Gem",
        "image": "",
        "properties": [],
    },
    {
        "name": "Chipped Amethyst",
        "type": "Gem",
        "image": "",
        "properties": [],
    },
    {
        "name": "Chipped Diamond",
        "type": "Gem",
        "image": "",
        "properties": [],
    },
    {
        "name": "Chipped Skull",
        "type": "Gem",
        "image": "",
        "properties": [],
    },
    {
        "name": "Flawed Ruby",
        "type": "Gem",
        "image": "",
        "properties": [],
    },
    {
        "name": "Flawed Emerald",
        "type": "Gem",
        "image": "",
        "properties": [],
    },
    {
        "name": "Flawed Sapphire",
        "type": "Gem",
        "image": "",
        "properties": [],
    },
    {
        "name": "Flawed Topaz",
        "type": "Gem",
        "image": "",
        "properties": [],
    },
    {
        "name": "Flawed Amethyst",
        "type": "Gem",
        "image": "",
        "properties": [],
    },
    {
        "name": "Flawed Diamond",
        "type": "Gem",
        "image": "",
        "properties": [],
    },
    {
        "name": "Flawed Skull",
        "type": "Gem",
        "image": "",
        "properties": [],
    },
    {
        "name": "Ruby",
        "type": "Gem",
        "image": "",
        "properties": [],
    },
    {
        "name": "Emerald",
        "type": "Gem",
        "image": "",
        "properties": [],
    },
    {
        "name": "Sapphire",
        "type": "Gem",
        "image": "",
        "properties": [],
    },
    {
        "name": "Topaz",
        "type": "Gem",
        "image": "",
        "properties": [],
    },
    {
        "name": "Amethyst",
        "type": "Gem",
        "image": "",
        "properties": [],
    },
    {
        "name": "Diamond",
        "type": "Gem",
        "image": "",
        "properties": [],
    },
    {
        "name": "Skull",
        "type": "Gem",
        "image": "",
        "properties": [],
    },
    {
        "name": "Flawless Ruby",
        "type": "Gem",
        "image": "",
        "properties": [],
    },
    {
        "name": "Flawless Emerald",
        "type": "Gem",
        "image": "",
        "properties": [],
    },
    {
        "name": "Flawless Sapphire",
        "type": "Gem",
        "image": "",
        "properties": [],
    },
    {
        "name": "Flawless Topaz",
        "type": "Gem",
        "image": "",
        "properties": [],
    },
    {
        "name": "Flawless Amethyst",
        "type": "Gem",
        "image": "",
        "properties": [],
    },
    {
        "name": "Flawless Diamond",
        "type": "Gem",
        "image": "",
        "properties": [],
    },
    {
        "name": "Flawless Skull",
        "type": "Gem",
        "image": "",
        "properties": [],
    },
    {
        "name": "Perfect Ruby",
        "type": "Gem",
        "image": "",
        "properties": [],
    },
    {
        "name": "Perfect Emerald",
        "type": "Gem",
        "image": "",
        "properties": [],
    },
    {
        "name": "Perfect Sapphire",
        "type": "Gem",
        "image": "",
        "properties": [],
    },
    {
        "name": "Perfect Topaz",
        "type": "Gem",
        "image": "",
        "properties": [],
    },
    {
        "name": "Perfect Amethyst",
        "type": "Gem",
        "image": "",
        "properties": [],
    },
    {
        "name": "Perfect Diamond",
        "type": "Gem",
        "image": "",
        "properties": [],
    },
    {
        "name": "Perfect Skull",
        "type": "Gem",
        "image": "",
        "properties": [],
    },
    {
        "name": "Full Rejuvenation",
        "type": "Potion",
        "image": "",
        "properties": [],
    },
    {
        "name": "Key of Destruction",
        "type": "Misc",
        "image": "",
        "properties": [],
    },
    {
        "name": "Key of Terror",
        "type": "Misc",
        "image": "",
        "properties": [],
    },
    {
        "name": "Key of Hatred",
        "type": "Misc",
        "image": "",
        "properties": [],
    },
    {
        "name": "3x3 Keyset",
        "type": "Misc",
        "image": "",
        "properties": [],
    },
    {
        "name": "Twisted Essence of Suffering",
        "type": "Misc",
        "image": "",
        "properties": [],
    },
    {
        "name": "Burning Essence of Terror",
        "type": "Misc",
        "image": "",
        "properties": [],
    },
    {
        "name": "Charged Essence of Hatred",
        "type": "Misc",
        "image": "",
        "properties": [],
    },
    {
        "name": "Festering Essence of Destruction",
        "type": "Misc",
        "image": "",
        "properties": [],
    },
    {
        "name": "Token of Absolution",
        "type": "Misc",
        "image": "",
        "properties": [],
    },
];

export default miscItems;