const pathToImage = "../assets/images/d2items/runes";

// Object Array of all the runes in the game
const runes = [
  {
    name: "El Rune",
    type: "Rune",
    image: `${pathToImage}/El_Rune.webp`,
    properties: [],
  },
  {
    name: "Eld Rune",
    type: "Rune",
    image: `${pathToImage}/Eld_Rune.webp`,
    properties: [],
  },
  {
    name: "Tir Rune",
    type: "Rune",
    image: `${pathToImage}/Tir_Rune.webp`,
    properties: [],
  },
  {
    name: "Nef Rune",
    type: "Rune",
    image: `${pathToImage}/Nef_Rune.webp`,
    properties: [],
  },
  {
    name: "Eth Rune",
    type: "Rune",
    image: `${pathToImage}/Eth_Rune.webp`,
    properties: [],
  },
  {
    name: "Ith Rune",
    type: "Rune",
    image: `${pathToImage}/Ith_Rune.webp`,
    properties: [],
  },
  {
    name: "Tal Rune",
    type: "Rune",
    image: `${pathToImage}/Tal_Rune.webp`,
    properties: [],
  },
  {
    name: "Ral Rune",
    type: "Rune",
    image: `${pathToImage}/Ral_Rune.webp`,
    properties: [],
  },
  {
    name: "Ort Rune",
    type: "Rune",
    image: `${pathToImage}/Ort_Rune.webp`,
    properties: [],
  },
  {
    name: "Thul Rune",
    type: "Rune",
    image: `${pathToImage}/Thul_Rune.webp`,
    properties: [],
  },
  {
    name: "Amn Rune",
    type: "Rune",
    image: `${pathToImage}/Amn_Rune.webp`,
    properties: [],
  },
  {
    name: "Sol Rune",
    type: "Rune",
    image: `${pathToImage}/Sol_Rune.webp`,
    properties: [],
  },
  {
    name: "Shael Rune",
    type: "Rune",
    image: `${pathToImage}/Shael_Rune.webp`,
    properties: [],
  },
  {
    name: "Dol Rune",
    type: "Rune",
    image: `${pathToImage}/Dol_Rune.webp`,
    properties: [],
  },
  {
    name: "Hel Rune",
    type: "Rune",
    image: `${pathToImage}/Hel_Rune.webp`,
    properties: [],
  },
  {
    name: "Io Rune",
    type: "Rune",
    image: `${pathToImage}/Io_Rune.webp`,
    properties: [],
  },
  {
    name: "Lum Rune",
    type: "Rune",
    image: `${pathToImage}/Lum_Rune.webp`,
    properties: [],
  },
  {
    name: "Ko Rune",
    type: "Rune",
    image: `${pathToImage}/Ko_Rune.webp`,
    properties: [],
  },
  {
    name: "Fal Rune",
    type: "Rune",
    image: `${pathToImage}/Fal_Rune.webp`,
    properties: [],
  },
  {
    name: "Lem Rune",
    type: "Rune",
    image: `${pathToImage}/Lem_Rune.webp`,
    properties: [],
  },
  {
    name: "Pul Rune",
    type: "Rune",
    image: `${pathToImage}/Pul_Rune.webp`,
    properties: [],
  },
  {
    name: "Um Rune",
    type: "Rune",
    image: `${pathToImage}/Um_Rune.webp`,
    properties: [],
  },
  {
    name: "Mal Rune",
    type: "Rune",
    image: `${pathToImage}/Mal_Rune.webp`,
    properties: [],
  },
  {
    name: "Ist Rune",
    type: "Rune",
    image: `${pathToImage}/Ist_Rune.webp`,
    properties: [],
  },
  {
    name: "Gul Rune",
    type: "Rune",
    image: `${pathToImage}/Gul_Rune.webp`,
    properties: [],
  },
  {
    name: "Vex Rune",
    type: "Rune",
    image: `${pathToImage}/Vex_Rune.webp`,
    properties: [],
  },
  {
    name: "Ohm Rune",
    type: "Rune",
    image: `${pathToImage}/Ohm_Rune.webp`,
    properties: [],
  },
  {
    name: "Lo Rune",
    type: "Rune",
    image: `${pathToImage}/Lo_Rune.webp`,
    properties: [],
  },
  {
    name: "Sur Rune",
    type: "Rune",
    image: `${pathToImage}/Sur_Rune.webp`,
    properties: [],
  },
  {
    name: "Ber Rune",
    type: "Rune",
    image: `${pathToImage}/Ber_Rune.webp`,
    properties: [],
  },
  {
    name: "Jah Rune",
    type: "Rune",
    image: `${pathToImage}/Jah_Rune.webp`,
    properties: [],
  },
  {
    name: "Cham Rune",
    type: "Rune",
    image: `${pathToImage}/Cham_Rune.webp`,
    properties: [],
  },
  {
    name: "Zod Rune",
    type: "Rune",
    image: `${pathToImage}/Zod_Rune.webp`,
    properties: [],
  },
];

export default runes;
