const pathToImage = 'assets/images/d2items/set';

// Object Array of all the runes in the game
const SetItems = [
    {
        "name": "Sigon's Shelter",
        "type": "Set Item",
        "image": `${pathToImage}/Sigon's_Shelter.webp`,
        "properties": [],
    },
    {
        "name": "Sigon's Visor",
        "type": "Set Item",
        "image": `${pathToImage}/Sigon's_Visor.webp`,
        "properties": [],
    },
    {
        "name": "Sigon's Guard",
        "type": "Set Item",
        "image": `${pathToImage}/Sigon's_Guard.webp`,
        "properties": [],
    },
    {
        "name": "Sigon's Gage",
        "type": "Set Item",
        "image": `${pathToImage}/Sigon's_Gage.webp`,
        "properties": [],
    },
    {
        "name": "Sigon's Sabot",
        "type": "Set Item",
        "image": `${pathToImage}/Sigon's_Sabot.webp`,
        "properties": [],
    },
    {
        "name": "Sigon's Wrap",
        "type": "Set Item",
        "image": `${pathToImage}/Sigon's_Wrap.webp`,
        "properties": [],
    },
    {
        "name": "Sigon's Steel Set",
        "type": "Set Item",
        "image": `${pathToImage}/Sigon's_Complete_Steel_Set.webp`,
        "properties": [],
    },
    {
        "name": "Aldur's Rhythm",
        "type": "Set Item",
        "image": `${pathToImage}/Aldur's_Rhythm.webp`,
        "properties": [],
    },
    {
        "name": "Aldur's Stony Gaze",
        "type": "Set Item",
        "image": `${pathToImage}/Aldur's_Stony_Gaze.webp`,
        "properties": [],
    },
    {
        "name": "Aldur's Deception",
        "type": "Set Item",
        "image": `${pathToImage}/Aldur's_Deception.webp`,
        "properties": [],
    },
    {
        "name": "Aldur's Advance",
        "type": "Set Item",
        "image": `${pathToImage}/Aldur's_Advance.webp`,
        "properties": [],
    },
    {
        "name": "Aldur's Watchtower Set",
        "type": "Set Item",
        "image": '',
        "properties": [],
    },
    {
        "name": "Milabrega's Rod",
        "type": "Set Item",
        "image": `${pathToImage}/Milabrega's_Rod.webp`,
        "properties": [],
    },
    {
        "name": "Milabrega's Robe",
        "type": "Set Item",
        "image": `${pathToImage}/Milabrega's_Robe.webp`,
        "properties": [],
    },
    {
        "name": "Milabrega's Diadem",
        "type": "Set Item",
        "image": `${pathToImage}/Milabrega's_Diadem.webp`,
        "properties": [],
    },
    {
        "name": "Milabrega's Orb",
        "type": "Set Item",
        "image": `${pathToImage}/Milabrega's_Orb.webp`,
        "properties": [],
    },
    {
        "name": "Milabrega's Regalia Set",
        "type": "Set Item",
        "image": "",
        "properties": [],
    },
    {
        "name": "Arctic Mitts",
        "type": "Set Item",
        "image": `${pathToImage}/Arctic_Mitts.webp`,
        "properties": [],
    },
    {
        "name": "Arctic Binding",
        "type": "Set Item",
        "image": `${pathToImage}/Arctic_Binding.webp`,
        "properties": [],
    },
    {
        "name": "Arctic Furs",
        "type": "Set Item",
        "image": `${pathToImage}/Arctic_Furs.webp`,
        "properties": [],
    },
    {
        "name": "Arctic Horn",
        "type": "Set Item",
        "image": `${pathToImage}/Arctic_Horn.webp`,
        "properties": [],
    },
    {
        "name": "Arctic Gear Set",
        "type": "Set Item",
        "image": "",
        "properties": [],
    },
    {
        "name": "Cathan's Visage",
        "type": "Set Item",
        "image": `${pathToImage}/Cathan's_Visage.webp`,
        "properties": [],
    },
    {
        "name": "Cathan's Rule",
        "type": "Set Item",
        "image": `${pathToImage}/Cathan's_Rule.webp`,
        "properties": [],
    },
    {
        "name": "Cathan's Seal",
        "type": "Set Item",
        "image": `${pathToImage}/Cathan's_Seal.webp`,
        "properties": [],
    },
    {
        "name": "Cathan's Sigil",
        "type": "Set Item",
        "image": `${pathToImage}/Cathan's_Sigil.webp`,
        "properties": [],
    },
    {
        "name": "Cathan's Mesh",
        "type": "Set Item",
        "image": `${pathToImage}/Cathan's_Mesh.webp`,
        "properties": [],
    },
    {
        "name": "Cathan's Traps Set",
        "type": "Set Item",
        "image": "",
        "properties": [],
    },
    {
        "name": "Trang-Oul's Guise",
        "type": "Set Item",
        "image": `${pathToImage}/Trang-Oul's_Guise.webp`,
        "properties": [],
    },
    {
        "name": "Trang-Oul's Scales",
        "type": "Set Item",
        "image": `${pathToImage}/Trang-Oul's_Scales.webp`,
        "properties": [],
    },
    {
        "name": "Trang-Oul's Girth",
        "type": "Set Item",
        "image": `${pathToImage}/Trang-Oul's_Girth.webp`,
        "properties": [],
    },
    {
        "name": "Trang-Oul's Claws",
        "type": "Set Item",
        "image": `${pathToImage}/Trang-Oul's_Claws.webp`,
        "properties": [],
    },
    {
        "name": "Trang-Oul's Wing",
        "type": "Set Item",
        "image": `${pathToImage}/Trang-Oul's_Wing.webp`,
        "properties": [],
    },
    {
        "name": "Trang-Oul's Avatar Set",
        "type": "Set Item",
        "image": "",
        "properties": [],
    },
    {
        "name": "Isenhart's Lightbrand",
        "type": "Set Item",
        "image": `${pathToImage}/Isenhart's_Lightbrand.webp`,
        "properties": [],
    },
    {
        "name": "Isenhart's Case",
        "type": "Set Item",
        "image": `${pathToImage}/Isenhart's_Case.webp`,
        "properties": [],
    },
    {
        "name": "Isenhart's Horns",
        "type": "Set Item",
        "image": `${pathToImage}/Isenhart's_Horns.webp`,
        "properties": [],
    },
    {
        "name": "Isenhart's Parry",
        "type": "Set Item",
        "image": `${pathToImage}/Isenhart's_Parry.webp`,
        "properties": [],
    },
    {
        "name": "Isenhart's Armory Set",
        "type": "Set Item",
        "image": "",
        "properties": [],
    },
    {
        "name": "Angelic Wings",
        "type": "Set Item",
        "image": `${pathToImage}/Angelic_Wings.webp`,
        "properties": [],
    },
    {
        "name": "Angelic Halo",
        "type": "Set Item",
        "image": `${pathToImage}/Angelic_Halo.webp`,
        "properties": [],
    },
    {
        "name": "Angelic Mantle",
        "type": "Set Item",
        "image": `${pathToImage}/Angelic_Mantle.webp`,
        "properties": [],
    },
    {
        "name": "Angelic Sickle",
        "type": "Set Item",
        "image": `${pathToImage}/Angelic_Sickle.webp`,
        "properties": [],
    },
    {
        "name": "Angelic Raiment Set",
        "type": "Set Item",
        "image": "",
        "properties": [],
    },
    {
        "name": "Immortal King's Stone Crusher",
        "type": "Set Item",
        "image": `${pathToImage}/Immortal_King's_Stone_Crusher.webp`,
        "properties": [],
    },
    {
        "name": "Immortal King's Detail",
        "type": "Set Item",
        "image": `${pathToImage}/Immortal_King's_Detail.webp`,
        "properties": [],
    },
    {
        "name": "Immortal King's Will",
        "type": "Set Item",
        "image": `${pathToImage}/Immortal_King's_Will.webp`,
        "properties": [],
    },
    {
        "name": "Immortal King's Soul Cage",
        "type": "Set Item",
        "image": `${pathToImage}/Immortal_King's_Soul_Cage.webp`,
        "properties": [],
    },
    {
        "name": "Immortal King's Forge",
        "type": "Set Item",
        "image": `${pathToImage}/Immortal_King's_Forge.webp`,
        "properties": [],
    },
    {
        "name": "Immortal King's Pillar",
        "type": "Set Item",
        "image": `${pathToImage}/Immortal_King's_Pillar.webp`,
        "properties": [],
    },
    {
        "name": "Immortal King Set",
        "type": "Set Item",
        "image": "",
        "properties": [],
    },
    {
        "name": "Tal Rasha's Adjudication",
        "type": "Set Item",
        "image": `${pathToImage}/Tal_Rasha's_Adjudication.webp`,
        "properties": [],
    },
    {
        "name": "Tal Rasha's Lidless Eye",
        "type": "Set Item",
        "image": `${pathToImage}/Tal_Rasha's_Lidless_Eye.webp`,
        "properties": [],
    },
    {
        "name": "Tal Rasha's Guardianship",
        "type": "Set Item",
        "image": `${pathToImage}/Tal_Rasha's_Guardianship.webp`,
        "properties": [],
    },
    {
        "name": "Tal Rasha's Horadric Crest",
        "type": "Set Item",
        "image": `${pathToImage}/Tal_Rasha's_Horadric_Crest.webp`,
        "properties": [],
    },
    {
        "name": "Tal Rasha's Fine-Spun Cloth",
        "type": "Set Item",
        "image": `${pathToImage}/Tal_Rasha's_Fine-Spun_Cloth.webp`,
        "properties": [],
    },
    {
        "name": "Tal Rasha's Wrappings Set",
        "type": "Set Item",
        "image": "",
        "properties": [],
    },
    {
        "name": "Sander's Superstition",
        "type": "Set Item",
        "image": `${pathToImage}/Sander's_Superstition.webp`,
        "properties": [],
    },
    {
        "name": "Sander's Paragon",
        "type": "Set Item",
        "image": `${pathToImage}/Sander's_Paragon.webp`,
        "properties": [],
    },
    {
        "name": "Sander's Taboo",
        "type": "Set Item",
        "image": `${pathToImage}/Sander's_Taboo.webp`,
        "properties": [],
    },
    {
        "name": "Sander's Riprap",
        "type": "Set Item",
        "image": `${pathToImage}/Sander's_Riprap.webp`,
        "properties": [],
    },
    {
        "name": "Sander's Folly Set",
        "type": "Set Item",
        "image": "",
        "properties": [],
    },
    {
        "name": "Berserker's Hatchet",
        "type": "Set Item",
        "image": `${pathToImage}/Berserker's_Hatchet.webp`,
        "properties": [],
    },
    {
        "name": "Berserker's Hauberk",
        "type": "Set Item",
        "image": `${pathToImage}/Berserker's_Hauberk.webp`,
        "properties": [],
    },
    {
        "name": "Berserker's Headgear",
        "type": "Set Item",
        "image": `${pathToImage}/Berserker's_Headgear.webp`,
        "properties": [],
    },
    {
        "name": "Berserker's Arsenal Set",
        "type": "Set Item",
        "image": "",
        "properties": [],
    },
    {
        "name": "Cow King's Horns",
        "type": "Set Item",
        "image": `${pathToImage}/Cow_King's_Horns.webp`,
        "properties": [],
    },
    {
        "name": "Cow King's Hide",
        "type": "Set Item",
        "image": `${pathToImage}/Cow_King's_Hide.webp`,
        "properties": [],
    },
    {
        "name": "Cow King's Hooves",
        "type": "Set Item",
        "image": `${pathToImage}/Cow_King's_Hooves.webp`,
        "properties": [],
    },
    {
        "name": "Cow King's Leathers Set",
        "type": "Set Item",
        "image": "",
        "properties": [],
    },
    {
        "name": "Whitstan's Guard",
        "type": "Set Item",
        "image": `${pathToImage}/Whitstan's_Guard.webp`,
        "properties": [],
    },
    {
        "name": "Guillaume's Face",
        "type": "Set Item",
        "image": `${pathToImage}/Guillaume's_Face.webp`,
        "properties": [],
    },
    {
        "name": "Wilhelm's Pride",
        "type": "Set Item",
        "image": `${pathToImage}/Wilhelm's_Pride.webp`,
        "properties": [],
    },
    {
        "name": "Magnus's Skin",
        "type": "Set Item",
        "image": `${pathToImage}/Magnus's_Skin.webp`,
        "properties": [],
    },
    {
        "name": "Orphan's Call Set",
        "type": "Set Item",
        "image": "",
        "properties": [],
    },
    {
        "name": "Sazabi's Cobalt Redeemer",
        "type": "Set Item",
        "image": `${pathToImage}/Sazabi's_Cobalt_Redeemer.webp`,
        "properties": [],
    },
    {
        "name": "Sazabi's Ghost Liberator",
        "type": "Set Item",
        "image": `${pathToImage}/Sazabi's_Ghost_Liberator.webp`,
        "properties": [],
    },
    {
        "name": "Sazabi's Mental Sheath",
        "type": "Set Item",
        "image": `${pathToImage}/Sazabi's_Mental_Sheath.webp`,
        "properties": [],
    },
    {
        "name": "Sazabi's Grand Tribute Set",
        "type": "Set Item",
        "image": "",
        "properties": [],
    },
    {
        "name": "M'avina's Caster",
        "type": "Set Item",
        "image": `${pathToImage}/M'avina's_Caster.webp`,
        "properties": [],
    },
    {
        "name": "M'avina's Embrace",
        "type": "Set Item",
        "image": `${pathToImage}/M'avina's_Embrace.webp`,
        "properties": [],
    },
    {
        "name": "M'avina's True Sight",
        "type": "Set Item",
        "image": `${pathToImage}/M'avina's_True_Sight.webp`,
        "properties": [],
    },
    {
        "name": "M'avina's Tenet",
        "type": "Set Item",
        "image": `${pathToImage}/M'avina's_Tenet.webp`,
        "properties": [],
    },
    {
        "name": "M'avina's Icy Clutch",
        "type": "Set Item",
        "image": `${pathToImage}/M'avina's_Icy_Clutch.webp`,
        "properties": [],
    },
    {
        "name": "M'avina's Battle Hymn Set",
        "type": "Set Item",
        "image": "",
        "properties": [],
    },
    {
        "name": "Naj's Circlet",
        "type": "Set Item",
        "image": `${pathToImage}/Naj's_Circlet.webp`,
        "properties": [],
    },
    {
        "name": "Naj's Light Plate",
        "type": "Set Item",
        "image": `${pathToImage}/Naj's_Light_Plate.webp`,
        "properties": [],
    },
    {
        "name": "Naj's Puzzler",
        "type": "Set Item",
        "image": `${pathToImage}/Naj's_Puzzler.webp`,
        "properties": [],
    },
    {
        "name": "Naj's Ancient Vestige Set",
        "type": "Set Item",
        "image": "",
        "properties": [],
    },
    {
        "name": "Dagoon's Teaching",
        "type": "Set Item",
        "image": `${pathToImage}/Dagoon's_Teaching.webp`,
        "properties": [],
    },
    {
        "name": "Haemosu's Adamant",
        "type": "Set Item",
        "image": `${pathToImage}/Haemosu's_Adamant.webp`,
        "properties": [],
    },
    {
        "name": "Taebaek's Glory",
        "type": "Set Item",
        "image": `${pathToImage}/Taebaek's_Glory.webp`,
        "properties": [],
    },
    {
        "name": "Ondal's Almighty",
        "type": "Set Item",
        "image": `${pathToImage}/Ondal's_Almighty.webp`,
        "properties": [],
    },
    {
        "name": "Heaven's Brethren Set",
        "type": "Set Item",
        "image": "",
        "properties": [],
    },
    {
        "name": "Hwanin's Justice",
        "type": "Set Item",
        "image": `${pathToImage}/Hwanin's_Justice.webp`,
        "properties": [],
    },
    {
        "name": "Hwanin's Refuge",
        "type": "Set Item",
        "image": `${pathToImage}/Hwanin's_Refuge.webp`,
        "properties": [],
    },
    {
        "name": "Hwanin's Splendor",
        "type": "Set Item",
        "image": `${pathToImage}/Hwanin's_Splendor.webp`,
        "properties": [],
    },
    {
        "name": "Hwanin's Blessing",
        "type": "Set Item",
        "image": `${pathToImage}/Hwanin's_Blessing.webp`,
        "properties": [],
    },
    {
        "name": "Hwanin's Majesty Set",
        "type": "Set Item",
        "image": "",
        "properties": [],
    },
    {
        "name": "Bul-Kathos's Sacred Charge",
        "type": "Set Item",
        "image": `${pathToImage}/Bul-Kathos's_Sacred_Charge.webp`,
        "properties": [],
    },
    {
        "name": "Bul-Kathos's Tribal Guardian",
        "type": "Set Item",
        "image": `${pathToImage}/Bul-Kathos's_Tribal_Guardian.webp`,
        "properties": [],
    },
    {
        "name": "Bul-Kathos's Children Set",
        "type": "Set Item",
        "image": "",
        "properties": [],
    },
    {
        "name": "Death's Touch",
        "type": "Set Item",
        "image": `${pathToImage}/Death's_Touch.webp`,
        "properties": [],
    },
    {
        "name": "Death's Guard",
        "type": "Set Item",
        "image": `${pathToImage}/Death's_Guard.webp`,
        "properties": [],
    },
    {
        "name": "Death's Hand",
        "type": "Set Item",
        "image": `${pathToImage}/Death's_Hand.webp`,
        "properties": [],
    },
    {
        "name": "Death's Disguise Set",
        "type": "Set Item",
        "image": "",
        "properties": [],
    },
    {
        "name": "Tancred's Skull",
        "type": "Set Item",
        "image": `${pathToImage}/Tancred's_Skull.webp`,
        "properties": [],
    },
    {
        "name": "Tancred's Weird",
        "type": "Set Item",
        "image": `${pathToImage}/Tancred's_Weird.webp`,
        "properties": [],
    },
    {
        "name": "Tancred's Hobnails",
        "type": "Set Item",
        "image": `${pathToImage}/Tancred's_Hobnails.webp`,
        "properties": [],
    },
    {
        "name": "Tancred's Spine",
        "type": "Set Item",
        "image": `${pathToImage}/Tancred's_Spine.webp`,
        "properties": [],
    },
    {
        "name": "Tancred's Crowbill",
        "type": "Set Item",
        "image": `${pathToImage}/Tancred's_Crowbill.webp`,
        "properties": [],
    },
    {
        "name": "Tancred's Battle Set",
        "type": "Set Item",
        "image": "",
        "properties": [],
    },
    {
        "name": "Iratha's Coil",
        "type": "Set Item",
        "image": `${pathToImage}/Iratha's_Coil.webp`,
        "properties": [],
    },
    {
        "name": "Iratha's Cuff",
        "type": "Set Item",
        "image": `${pathToImage}/Iratha's_Cuff.webp`,
        "properties": [],
    },
    {
        "name": "Iratha's Cord",
        "type": "Set Item",
        "image": `${pathToImage}/Iratha's_Cord.webp`,
        "properties": [],
    },
    {
        "name": "Iratha's Collar",
        "type": "Set Item",
        "image": `${pathToImage}/Iratha's_Collar.webp`,
        "properties": [],
    },
    {
        "name": "Iratha's Finery Set",
        "type": "Set Item",
        "image": "",
        "properties": [],
    },
    {
        "name": "Infernal Sign",
        "type": "Set Item",
        "image": `${pathToImage}/Infernal_Sign.webp`,
        "properties": [],
    },
    {
        "name": "Infernal Torch",
        "type": "Set Item",
        "image": `${pathToImage}/Infernal_Torch.webp`,
        "properties": [],
    },
    {
        "name": "Infernal Cranium",
        "type": "Set Item",
        "image": `${pathToImage}/Infernal_Cranium.webp`,
        "properties": [],
    },
    {
        "name": "Infernal Tools Set",
        "type": "Set Item",
        "image": "",
        "properties": [],
    },
    {
        "name": "Hsarus' Iron Stay",
        "type": "Set Item",
        "image": `${pathToImage}/"Hsarus'_Iron_Stay.webp`,
        "properties": [],
    },
    {
        "name": "Hsarus' Iron Fist",
        "type": "Set Item",
        "image": `${pathToImage}/Hsarus'_Iron_Fist.webp`,
        "properties": [],
    },
    {
        "name": "Hsarus' Iron Heel",
        "type": "Set Item",
        "image": `${pathToImage}/Hsarus'_Iron_Heel.webp`,
        "properties": [],
    },
    {
        "name": "Hsarus' Defense Set",
        "type": "Set Item",
        "image": "",
        "properties": [],
    },
    {
        "name": "Natalya's Mark",
        "type": "Set Item",
        "image": `${pathToImage}/Natalya's_Mark.webp`,
        "properties": [],
    },
    {
        "name": "Natalya's Shadow",
        "type": "Set Item",
        "image": `${pathToImage}/Natalya's_Shadow.webp`,
        "properties": [],
    },
    {
        "name": "Natalya's Totem",
        "type": "Set Item",
        "image": `${pathToImage}/Natalya's_Totem.webp`,
        "properties": [],
    },
    {
        "name": "Natalya's Soul",
        "type": "Set Item",
        "image": `${pathToImage}/Natalya's_Soul.webp`,
        "properties": [],
    },
    {
        "name": "Natalya's Odium Set",
        "type": "Set Item",
        "image": "",
        "properties": [],
    },
    {
        "name": "Cleglaw's Tooth",
        "type": "Set Item",
        "image": `${pathToImage}/Cleglaw's_Tooth.webp`,
        "properties": [],
    },
    {
        "name": "Cleglaw's Claw",
        "type": "Set Item",
        "image": `${pathToImage}/Cleglaw's_Claw.webp`,
        "properties": [],
    },
    {
        "name": "Cleglaw's Pincers",
        "type": "Set Item",
        "image": `${pathToImage}/Cleglaw's_Pincers.webp`,
        "properties": [],
    },
    {
        "name": "Cleglaw's Brace Set",
        "type": "Set Item",
        "image": "",
        "properties": [],
    },
    {
        "name": "Griswold's Redemption",
        "type": "Set Item",
        "image": `${pathToImage}/Griswold's_Redemption.webp`,
        "properties": [],
    },
    {
        "name": "Griswold's Valor",
        "type": "Set Item",
        "image": `${pathToImage}/Griswold's_Valor.webp`,
        "properties": [],
    },
    {
        "name": "Griswold's Heart",
        "type": "Set Item",
        "image": `${pathToImage}/Griswold's_Heart.webp`,
        "properties": [],
    },
    {
        "name": "Griswold's Honor",
        "type": "Set Item",
        "image": `${pathToImage}/Griswold's_Honor.webp`,
        "properties": [],
    },
    {
        "name": "Griswold's Legacy Set",
        "type": "Set Item",
        "image": "",
        "properties": [],
    },
    {
        "name": "Dark Adherent",
        "type": "Set Item",
        "image": `${pathToImage}/Dark_Adherent.webp`,
        "properties": [],
    },
    {
        "name": "Credendum",
        "type": "Set Item",
        "image": `${pathToImage}/Credendum.webp`,
        "properties": [],
    },
    {
        "name": "Laying of Hands",
        "type": "Set Item",
        "image": `${pathToImage}/Laying_of_Hands.webp`,
        "properties": [],
    },
    {
        "name": "Rite of Passage",
        "type": "Set Item",
        "image": `${pathToImage}/Rite_of_Passage.webp`,
        "properties": [],
    },
    {
        "name": "Telling of Beads",
        "type": "Set Item",
        "image": `${pathToImage}/Telling_of_Beads.webp`,
        "properties": [],
    },
    {
        "name": "The Disciple Set",
        "type": "Set Item",
        "image": "",
        "properties": [],
    },
    {
        "name": "Civerb's Cudgel",
        "type": "Set Item",
        "image": `${pathToImage}/Civerb's_Cudgel.webp`,
        "properties": [],
    },
    {
        "name": "Civerb's Ward",
        "type": "Set Item",
        "image": `${pathToImage}/Civerb's_Ward.webp`,
        "properties": [],
    },
    {
        "name": "Civerb's Icon",
        "type": "Set Item",
        "image": `${pathToImage}/Civerb's_Icon.webp`,
        "properties": [],
    },
    {
        "name": "Civerb's Vestments Set",
        "type": "Set Item",
        "image": "",
        "properties": [],
    },
    {
        "name": "Arcanna's Sign",
        "type": "Set Item",
        "image": `${pathToImage}/Arcanna's_Sign.webp`,
        "properties": [],
    },
    {
        "name": "Arcanna's Head",
        "type": "Set Item",
        "image": `${pathToImage}/Arcanna's_Head.webp`,
        "properties": [],
    },
    {
        "name": "Arcanna's Flesh",
        "type": "Set Item",
        "image": `${pathToImage}/Arcanna's_Flesh.webp`,
        "properties": [],
    },
    {
        "name": "Arcanna's Deathwand",
        "type": "Set Item",
        "image": `${pathToImage}/Arcanna's_Deathwand.webp`,
        "properties": [],
    },
    {
        "name": "Arcanna's Tricks Set",
        "type": "Set Item",
        "image": "",
        "properties": [],
    },
    {
        "name": "Vidala's Snare",
        "type": "Set Item",
        "image": `${pathToImage}/Vidala's_Snare.webp`,
        "properties": [],
    },
    {
        "name": "Vidala's Ambush",
        "type": "Set Item",
        "image": `${pathToImage}/Vidala's_Ambush.webp`,
        "properties": [],
    },
    {
        "name": "Vidala's Fetlock",
        "type": "Set Item",
        "image": `${pathToImage}/Vidala's_Fetlock.webp`,
        "properties": [],
    },
    {
        "name": "Vidala's Barb",
        "type": "Set Item",
        "image": `${pathToImage}/Vidala's_Barb.webp`,
        "properties": [],
    },
    {
        "name": "Vidala's Rig Set",
        "type": "Set Item",
        "image": "",
        "properties": [],
    },
];

export default SetItems;