const pathToUniques = "../assets/images/d2items/uniques";
const pathToWeaponImages = `${pathToUniques}/weapons`;
const pathToArmorImages = `${pathToUniques}/armor`;
const pathToAccessoryImages = `${pathToUniques}/accessories`;
const pathToCharmImages = `${pathToUniques}/charms`;
const pathToJewelImages = `${pathToUniques}/jewels`;

// Object Array of all the uniques in the game
const uniques = [
  {
    name: "Annihilus",
    type: "small charm",
    image: `${pathToCharmImages}/Annihilus.webp`,
    properties: [],
  },
  {
    name: "Gheed's Fortune",
    type: "grand charm",
    image: `${pathToCharmImages}/Gheeds_Fortune.webp`,
    properties: [],
  },
  {
    name: "Hellfire Torch",
    type: "large charm",
    image: `${pathToCharmImages}/Hellfire_Torch.webp`,
    properties: [],
  },
  {
    name: "Rainbow Facet",
    type: "jewel",
    image: `${pathToJewelImages}/Blue_Facet.webp`,
    properties: [],
  },
  {
    name: "Bul-Kathos' Wedding Band",
    type: "ring",
    image: `${pathToAccessoryImages}/rings/Bul-Kathos'_Wedding_Band.webp`,
    properties: [],
  },
  {
    name: "Carrion Wind",
    type: "ring",
    image: `${pathToAccessoryImages}/rings/Carrion_Wind.webp`,
    properties: [],
  },
  {
    name: "Dwarf Star",
    type: "ring",
    image: `${pathToAccessoryImages}/rings/Dwarf_Star.webp`,
    properties: [],
  },
  {
    name: "Manald Heal",
    type: "ring",
    image: `${pathToAccessoryImages}/rings/Manald_Heal.webp`,
    properties: [],
  },
  {
    name: "Nagelring",
    type: "ring",
    image: `${pathToAccessoryImages}/rings/Nagelring.webp`,
    properties: [],
  },
  {
    name: "Nature's Peace",
    type: "ring",
    image: `${pathToAccessoryImages}/rings/Nature's_Peace.webp`,
    properties: [],
  },
  {
    name: "Raven Frost",
    type: "ring",
    image: `${pathToAccessoryImages}/rings/Raven_Frost.webp`,
    properties: [],
  },
  {
    name: "Stone of Jordan",
    type: "ring",
    image: `${pathToAccessoryImages}/rings/Stone_of_Jordan.webp`,
    properties: [],
  },
  {
    name: "Wisp Projector",
    type: "ring",
    image: `${pathToAccessoryImages}/rings/Wisp_Projector.webp`,
    properties: [],
  },
  {
    name: "Atma's Scarab",
    type: "amulet",
    image: `${pathToAccessoryImages}/amulets/Atma's_Scarab.webp`,
    properties: [],
  },
  {
    name: "Crescent Moon",
    type: "amulet",
    image: `${pathToAccessoryImages}/amulets/Crescent_Moon.webp`,
    properties: [],
  },
  {
    name: "Highlord's Wrath",
    type: "amulet",
    image: `${pathToAccessoryImages}/amulets/Highlord's_Wrath.webp`,
    properties: [],
  },
  {
    name: "Mara's Kaleidoscope",
    type: "amulet",
    image: `${pathToAccessoryImages}/amulets/Mara's_Kaleidoscope.webp`,
    properties: [],
  },
  {
    name: "Metalgrid",
    type: "amulet",
    image: `${pathToAccessoryImages}/amulets/Metalgrid.webp`,
    properties: [],
  },
  {
    name: "Nokozan Relic",
    type: "amulet",
    image: `${pathToAccessoryImages}/amulets/Nokozan_Relic.webp`,
    properties: [],
  },
  {
    name: "Saracen's Chance",
    type: "amulet",
    image: `${pathToAccessoryImages}/amulets/Saracen's_Chance.webp`,
    properties: [],
  },
  {
    name: "Seraph's Hymn",
    type: "amulet",
    image: `${pathToAccessoryImages}/amulets/Saracen's_Hymn.webp`,
    properties: [],
  },
  {
    name: "The Cat's Eye",
    type: "amulet",
    image: `${pathToAccessoryImages}/amulets/The_Cat's_Eye.webp`,
    properties: [],
  },
  {
    name: "The Eye of Etlich",
    type: "amulet",
    image: `${pathToAccessoryImages}/amulets/The_Eye_of_Etlich.webp`,
    properties: [],
  },
  {
    name: "The Mahim-Oak Curio",
    type: "amulet",
    image: `${pathToAccessoryImages}/amulets/The_Mahim-Oak_Curio.webp`,
    properties: [],
  },
  {
    name: "The Rising Sun",
    type: "amulet",
    image: `${pathToAccessoryImages}/amulets/The_Rising_Sun.webp`,
    properties: [],
  },
  {
    name: "Axe of Fechmar",
    type: "axe",
    image: `${pathToWeaponImages}/axes/Axe_of_Fechmar.webp`,
    properties: [],
  },
  {
    name: "Bladebone",
    type: "axe",
    image: `${pathToWeaponImages}/axes/Bladebone.webp`,
    properties: [],
  },
  {
    name: "Boneslayer Blade",
    type: "axe",
    image: `${pathToWeaponImages}/axes/Boneslayer_Blade.webp`,
    properties: [],
  },
  {
    name: "Brainhew",
    type: "axe",
    image: `${pathToWeaponImages}/axes/Brainhew.webp`,
    properties: [],
  },
  {
    name: "Butcher's Pupil",
    type: "axe",
    image: `${pathToWeaponImages}/axes/Butcher's_Pupil.webp`,
    properties: [],
  },
  {
    name: "Coldkill",
    type: "axe",
    image: `${pathToWeaponImages}/axes/Coldkill.webp`,
    properties: [],
  },
  {
    name: "Cranebeak",
    type: "axe",
    image: `${pathToWeaponImages}/axes/Cranebeak.webp`,
    properties: [],
  },
  {
    name: "Death Cleaver",
    type: "axe",
    image: `${pathToWeaponImages}/axes/Death_Cleaver.webp`,
    properties: [],
  },
  {
    name: "Deathspade",
    type: "axe",
    image: `${pathToWeaponImages}/axes/Deathspade.webp`,
    properties: [],
  },
  {
    name: "Ethereal Edge",
    type: "axe",
    image: `${pathToWeaponImages}/axes/Ethereal_Edge.webp`,
    properties: [],
  },
  {
    name: "Executioner's Justice",
    type: "axe",
    image: `${pathToWeaponImages}/axes/Executioner's_Justice.webp`,
    properties: [],
  },
  {
    name: "Goreshovel",
    type: "axe",
    image: `${pathToWeaponImages}/axes/Goreshovel.webp`,
    properties: [],
  },
  {
    name: "Guardian Naga",
    type: "axe",
    image: `${pathToWeaponImages}/axes/Guardian_Naga.webp`,
    properties: [],
  },
  {
    name: "Hellslayer",
    type: "axe",
    image: `${pathToWeaponImages}/axes/Hellslayer.webp`,
    properties: [],
  },
  {
    name: "Humongous",
    type: "axe",
    image: `${pathToWeaponImages}/axes/Humongous.webp`,
    properties: [],
  },
  {
    name: "Islestrike",
    type: "axe",
    image: `${pathToWeaponImages}/axes/Islestrike.webp`,
    properties: [],
  },
  {
    name: "Messerchmidt's Reaver",
    type: "axe",
    image: `${pathToWeaponImages}/axes/Messerchmidt's_Reaver.webp`,
    properties: [],
  },
  {
    name: "Pompeii's Wrath",
    type: "axe",
    image: `${pathToWeaponImages}/axes/Pompeii's_Wrath.webp`,
    properties: [],
  },
  {
    name: "Rakescar",
    type: "axe",
    image: `${pathToWeaponImages}/axes/Rakescar.webp`,
    properties: [],
  },
  {
    name: "Razor's Edge",
    type: "axe",
    image: `${pathToWeaponImages}/axes/Razor's_Edge.webp`,
    properties: [],
  },
  {
    name: "Rune Master",
    type: "axe",
    image: `${pathToWeaponImages}/axes/Rune_Master.webp`,
    properties: [],
  },
  {
    name: "Skull Splitter",
    type: "axe",
    image: `${pathToWeaponImages}/axes/Skull_Splitter.webp`,
    properties: [],
  },
  {
    name: "Spellsteel",
    type: "axe",
    image: `${pathToWeaponImages}/axes/Spellsteel.webp`,
    properties: [],
  },
  {
    name: "Stormrider",
    type: "axe",
    image: `${pathToWeaponImages}/axes/Stormrider.webp`,
    properties: [],
  },
  {
    name: "The Chieftain",
    type: "axe",
    image: `${pathToWeaponImages}/axes/The_Chieftain.webp`,
    properties: [],
  },
  {
    name: "The Gnasher",
    type: "axe",
    image: `${pathToWeaponImages}/axes/The_Gnasher.webp`,
    properties: [],
  },
  {
    name: "The Minotaur",
    type: "axe",
    image: `${pathToWeaponImages}/axes/The_Minotaur.webp`,
    properties: [],
  },
  {
    name: "Warlord's Trust",
    type: "axe",
    image: `${pathToWeaponImages}/axes/Warlord's_Trust.webp`,
    properties: [],
  },
  {
    name: "Blastbark",
    type: "bow",
    image: `${pathToWeaponImages}/bows/Blastbark.webp`,
    properties: [],
  },
  {
    name: "Cliffkiller",
    type: "bow",
    image: `${pathToWeaponImages}/bows/Cliffkiller.webp`,
    properties: [],
  },
  {
    name: "Eaglehorn",
    type: "bow",
    image: `${pathToWeaponImages}/bows/Eaglehorn.webp`,
    properties: [],
  },
  {
    name: "Endlesshail",
    type: "bow",
    image: `${pathToWeaponImages}/bows/Endlesshail.webp`,
    properties: [],
  },
  {
    name: "Goldstrike Arch",
    type: "bow",
    image: `${pathToWeaponImages}/bows/Goldstrike_Arch.webp`,
    properties: [],
  },
  {
    name: "Hellclap",
    type: "bow",
    image: `${pathToWeaponImages}/bows/Hellclap.webp`,
    properties: [],
  },
  {
    name: "Kuko Shukaku",
    type: "bow",
    image: `${pathToWeaponImages}/bows/Kuko_Shukaku.webp`,
    properties: [],
  },
  {
    name: "Magewrath",
    type: "bow",
    image: `${pathToWeaponImages}/bows/Magewrath.webp`,
    properties: [],
  },
  {
    name: "Pluckeye",
    type: "bow",
    image: `${pathToWeaponImages}/bows/Pluckeye.webp`,
    properties: [],
  },
  {
    name: "Raven Claw",
    type: "bow",
    image: `${pathToWeaponImages}/bows/Raven_Claw.webp`,
    properties: [],
  },
  {
    name: "Riphook",
    type: "bow",
    image: `${pathToWeaponImages}/bows/Riphook.webp`,
    properties: [],
  },
  {
    name: "Rogue's Bow",
    type: "bow",
    image: `${pathToWeaponImages}/bows/Rogue's_Bow.webp`,
    properties: [],
  },
  {
    name: "Skystrike",
    type: "bow",
    image: `${pathToWeaponImages}/bows/Skystrike.webp`,
    properties: [],
  },
  {
    name: "Stormstrike",
    type: "bow",
    image: `${pathToWeaponImages}/bows/Stormstrike.webp`,
    properties: [],
  },
  {
    name: "Widowmaker",
    type: "bow",
    image: `${pathToWeaponImages}/bows/Widowmaker.webp`,
    properties: [],
  },
  {
    name: "Windforce",
    type: "bow",
    image: `${pathToWeaponImages}/bows/Windforce.webp`,
    properties: [],
  },
  {
    name: "Witchwild String",
    type: "bow",
    image: `${pathToWeaponImages}/bows/Witchwild_String.webp`,
    properties: [],
  },
  {
    name: "Witherspring",
    type: "bow",
    image: `${pathToWeaponImages}/bows/Witherspring.webp`,
    properties: [],
  },
  {
    name: "Wizendraw",
    type: "bow",
    image: `${pathToWeaponImages}/bows/Wizendraw.webp`,
    properties: [],
  },
  {
    name: "Dark Clan Crusher",
    type: "club",
    image: `${pathToWeaponImages}/clubs/Dark_Clan_Crusher.webp`,
    properties: [],
  },
  {
    name: "Demon Limb",
    type: "club",
    image: `${pathToWeaponImages}/clubs/Demon_Limb.webp`,
    properties: [],
  },
  {
    name: "Felloak",
    type: "club",
    image: `${pathToWeaponImages}/clubs/Felloak.webp`,
    properties: [],
  },
  {
    name: "Fleshrender",
    type: "club",
    image: `${pathToWeaponImages}/clubs/Fleshrender.webp`,
    properties: [],
  },
  {
    name: "Nord's Tenderizer",
    type: "club",
    image: `${pathToWeaponImages}/clubs/Nord's_Tenderizer.webp`,
    properties: [],
  },
  {
    name: "Stoutnail",
    type: "club",
    image: `${pathToWeaponImages}/clubs/Stoutnail.webp`,
    properties: [],
  },
  {
    name: "Buriza-Do Kyanon",
    type: "crossbow",
    image: `${pathToWeaponImages}/crossbows/Buriza-Do_Kyanon.webp`,
    properties: [],
  },
  {
    name: "Demon Machine",
    type: "crossbow",
    image: `${pathToWeaponImages}/crossbows/Demon_Machine.webp`,
    properties: [],
  },
  {
    name: "Doomslinger",
    type: "crossbow",
    image: `${pathToWeaponImages}/crossbows/Doomslinger.webp`,
    properties: [],
  },
  {
    name: "Gut Siphon",
    type: "crossbow",
    image: `${pathToWeaponImages}/crossbows/Gut_Siphon.webp`,
    properties: [],
  },
  {
    name: "Hellcast",
    type: "crossbow",
    image: `${pathToWeaponImages}/crossbows/Hellcast.webp`,
    properties: [],
  },
  {
    name: "Hellrack",
    type: "crossbow",
    image: `${pathToWeaponImages}/crossbows/Hellrack.webp`,
    properties: [],
  },
  {
    name: "Ichorstring",
    type: "crossbow",
    image: `${pathToWeaponImages}/crossbows/Ichorstring.webp`,
    properties: [],
  },
  {
    name: "Langer Briser",
    type: "crossbow",
    image: `${pathToWeaponImages}/crossbows/Langer_Briser.webp`,
    properties: [],
  },
  {
    name: "Leadcrow",
    type: "crossbow",
    image: `${pathToWeaponImages}/crossbows/Leadcrow.webp`,
    properties: [],
  },
  {
    name: "Pus Spitter",
    type: "crossbow",
    image: `${pathToWeaponImages}/crossbows/Pus_Spitter.webp`,
    properties: [],
  },
  {
    name: "Blackdog's Sharp",
    type: "dagger",
    image: `${pathToWeaponImages}/daggers/Blackdog's_Sharp.webp`,
    properties: [],
  },
  {
    name: "Fleshripper",
    type: "dagger",
    image: `${pathToWeaponImages}/daggers/Fleshripper.webp`,
    properties: [],
  },
  {
    name: "Ghostflame",
    type: "dagger",
    image: `${pathToWeaponImages}/daggers/Ghostflame.webp`,
    properties: [],
  },
  {
    name: "Gull",
    type: "dagger",
    image: `${pathToWeaponImages}/daggers/Gull.webp`,
    properties: [],
  },
  {
    name: "Heart Carver",
    type: "dagger",
    image: `${pathToWeaponImages}/daggers/Heart_Carver.webp`,
    properties: [],
  },
  {
    name: "Spectral Shard",
    type: "dagger",
    image: `${pathToWeaponImages}/daggers/Spectral_Shard.webp`,
    properties: [],
  },
  {
    name: "Spineripper",
    type: "dagger",
    image: `${pathToWeaponImages}/daggers/Spineripper.webp`,
    properties: [],
  },
  {
    name: "Stormspike",
    type: "dagger",
    image: `${pathToWeaponImages}/daggers/Stormspike.webp`,
    properties: [],
  },
  {
    name: "The Diggler",
    type: "dagger",
    image: `${pathToWeaponImages}/daggers/The_Diggler.webp`,
    properties: [],
  },
  {
    name: "The Jade Tan Do",
    type: "dagger",
    image: `${pathToWeaponImages}/daggers/The_Jade_Tan_Do.webp`,
    properties: [],
  },
  {
    name: "Wizardspike",
    type: "dagger",
    image: `${pathToWeaponImages}/daggers/Wizardspike.webp`,
    properties: [],
  },
  {
    name: "Bloodtree Stump",
    type: "hammer",
    image: `${pathToWeaponImages}/hammers/Bloodtree_Stump.webp`,
    properties: [],
  },
  {
    name: "Bonesnap",
    type: "hammer",
    image: `${pathToWeaponImages}/hammers/Bonesnap.webp`,
    properties: [],
  },
  {
    name: "Earth Shifter",
    type: "hammer",
    image: `${pathToWeaponImages}/hammers/Earth_Shifter.webp`,
    properties: [],
  },
  {
    name: "Earthshaker",
    type: "hammer",
    image: `${pathToWeaponImages}/hammers/Earthshaker.webp`,
    properties: [],
  },
  {
    name: "Ironstone",
    type: "hammer",
    image: `${pathToWeaponImages}/hammers/Ironstone.webp`,
    properties: [],
  },
  {
    name: "Schaefer's Hammer",
    type: "hammer",
    image: `${pathToWeaponImages}/hammers/Schaefer's_Hammer.webp`,
    properties: [],
  },
  {
    name: "Steeldriver",
    type: "hammer",
    image: `${pathToWeaponImages}/hammers/Steeldriver.webp`,
    properties: [],
  },
  {
    name: "Stone Crusher",
    type: "hammer",
    image: `${pathToWeaponImages}/hammers/Stone_Crusher.webp`,
    properties: [],
  },
  {
    name: "The Cranium Basher",
    type: "hammer",
    image: `${pathToWeaponImages}/hammers/The_Cranium_Basher.webp`,
    properties: [],
  },
  {
    name: "The Gavel of Pain",
    type: "hammer",
    image: `${pathToWeaponImages}/hammers/The_Gavel_of_Pain.webp`,
    properties: [],
  },
  {
    name: "Windhammer",
    type: "hammer",
    image: `${pathToWeaponImages}/hammers/Windhammer.webp`,
    properties: [],
  },
  {
    name: "Demon's Arch",
    type: "javalin",
    image: `${pathToWeaponImages}/javalins/Demon's_Arch.webp`,
    properties: [],
  },
  {
    name: "Gargoyle's Bite",
    type: "javalin",
    image: `${pathToWeaponImages}/javalins/Gargoyle's_Bite.webp`,
    properties: [],
  },
  {
    name: "Thunderstroke",
    type: "javalin",
    image: `${pathToWeaponImages}/javalins/Thunderstroke.webp`,
    properties: [],
  },
  {
    name: "Titan's Revenge",
    type: "javalin",
    image: `${pathToWeaponImages}/javalins/Titan's_Revenge.webp`,
    properties: [],
  },
  {
    name: "Wraith Flight",
    type: "javalin",
    image: `${pathToWeaponImages}/javalins/Wraith_Flight.webp`,
    properties: [],
  },
  {
    name: "Bartuc's Cut-Throat",
    type: "katar",
    image: `${pathToWeaponImages}/katars/Bartuc's_Cut-Throat.webp`,
    properties: [],
  },
  {
    name: "Firelizard's Talons",
    type: "katar",
    image: `${pathToWeaponImages}/katars/Firelizard's_Talons.webp`,
    properties: [],
  },
  {
    name: "Jade Talons",
    type: "katar",
    image: `${pathToWeaponImages}/katars/Jade_Talons.webp`,
    properties: [],
  },
  {
    name: "Shadow Killer",
    type: "katar",
    image: `${pathToWeaponImages}/katars/Shadow_Killer.webp`,
    properties: [],
  },
  {
    name: "Baezil's Vortex",
    type: "mace",
    image: `${pathToWeaponImages}/maces/Baezil's_Vortex.webp`,
    properties: [],
  },
  {
    name: "Baranar's Star",
    type: "mace",
    image: `${pathToWeaponImages}/maces/Baranar's_Star.webp`,
    properties: [],
  },
  {
    name: "Bloodrise",
    type: "mace",
    image: `${pathToWeaponImages}/maces/Bloodrise.webp`,
    properties: [],
  },
  {
    name: "Crushflange",
    type: "mace",
    image: `${pathToWeaponImages}/maces/Crushflange.webp`,
    properties: [],
  },
  {
    name: "Horizon's Tornado",
    type: "mace",
    image: `${pathToWeaponImages}/maces/Horizon's_Tornado.webp`,
    properties: [],
  },
  {
    name: "Moonfall",
    type: "mace",
    image: `${pathToWeaponImages}/maces/Moonfall.webp`,
    properties: [],
  },
  {
    name: "Stormlash",
    type: "mace",
    image: `${pathToWeaponImages}/maces/Stormlash.webp`,
    properties: [],
  },
  {
    name: "Sureshrill Frost",
    type: "mace",
    image: `${pathToWeaponImages}/maces/Sureshrill_Frost.webp`,
    properties: [],
  },
  {
    name: "The General's Tan Do Li Ga",
    type: "mace",
    image: `${pathToWeaponImages}/maces/The_General's_Tan_Do_Li_Ga.webp`,
    properties: [],
  },
  {
    name: "Death's Fathom",
    type: "orb",
    image: `${pathToWeaponImages}/orbs/Death's_Fathom.webp`,
    properties: [],
  },
  {
    name: "Eschuta's Temper",
    type: "orb",
    image: `${pathToWeaponImages}/orbs/Eschuta's_Temper.webp`,
    properties: [],
  },
  {
    name: "The Oculus",
    type: "orb",
    image: `${pathToWeaponImages}/orbs/The_Oculus.webp`,
    properties: [],
  },
  {
    name: "Athena's Wrath",
    type: "polearm",
    image: `${pathToWeaponImages}/polearms/Athena's_Wrath.webp`,
    properties: [],
  },
  {
    name: "Blackreach Blade",
    type: "polearm",
    image: `${pathToWeaponImages}/polearms/Blackreach_Blade.webp`,
    properties: [],
  },
  {
    name: "Bonehew",
    type: "polearm",
    image: `${pathToWeaponImages}/polearms/Bonehew.webp`,
    properties: [],
  },
  {
    name: "Dimoak's Hew",
    type: "polearm",
    image: `${pathToWeaponImages}/polearms/Dimoak's_Hew.webp`,
    properties: [],
  },
  {
    name: "Grim's Burning Dead",
    type: "polearm",
    image: `${pathToWeaponImages}/polearms/Grim's_Burning_Dead.webp`,
    properties: [],
  },
  {
    name: "Husoldal Evo",
    type: "polearm",
    image: `${pathToWeaponImages}/polearms/Husoldal_Evo.webp`,
    properties: [],
  },
  {
    name: "Pierre Tombale Couant",
    type: "polearm",
    image: `${pathToWeaponImages}/polearms/Pierre_Tombale_Couant.webp`,
    properties: [],
  },
  {
    name: "Soul Harvest",
    type: "polearm",
    image: `${pathToWeaponImages}/polearms/Soul_Harvest.webp`,
    properties: [],
  },
  {
    name: "Steelgoad",
    type: "polearm",
    image: `${pathToWeaponImages}/polearms/Steelgoad.webp`,
    properties: [],
  },
  {
    name: "Stormspire",
    type: "polearm",
    image: `${pathToWeaponImages}/polearms/Stormspire.webp`,
    properties: [],
  },
  {
    name: "The Battlebranch",
    type: "polearm",
    image: `${pathToWeaponImages}/polearms/The_Battlebranch.webp`,
    properties: [],
  },
  {
    name: "The Grim Reaper",
    type: "polearm",
    image: `${pathToWeaponImages}/polearms/The_Grim_Reaper.webp`,
    properties: [],
  },
  {
    name: "The Meat Scrapper",
    type: "polearm",
    image: `${pathToWeaponImages}/polearms/The_Meat_Scrapper.webp`,
    properties: [],
  },
  {
    name: "The Reaper's Toll",
    type: "polearm",
    image: `${pathToWeaponImages}/polearms/The_Reaper's_Toll.webp`,
    properties: [],
  },
  {
    name: "Tomb Reaver",
    type: "polearm",
    image: `${pathToWeaponImages}/polearms/Tomb_Reaver.webp`,
    properties: [],
  },
  {
    name: "Woestave",
    type: "polearm",
    image: `${pathToWeaponImages}/polearms/Woestave.webp`,
    properties: [],
  },
  {
    name: "Astreon's Iron Ward",
    type: "sceptor",
    image: `${pathToWeaponImages}/sceptors/Astreon's_Iron_Ward.webp`,
    properties: [],
  },
  {
    name: "Hand of Blessed Light",
    type: "sceptor",
    image: `${pathToWeaponImages}/sceptors/Hand_of_Blessed_Light.webp`,
    properties: [],
  },
  {
    name: "Heaven's Light",
    type: "sceptor",
    image: `${pathToWeaponImages}/sceptors/Heaven's_Light.webp`,
    properties: [],
  },
  {
    name: "Knell Striker",
    type: "sceptor",
    image: `${pathToWeaponImages}/sceptors/Knell_Striker.webp`,
    properties: [],
  },
  {
    name: "Rusthandle",
    type: "sceptor",
    image: `${pathToWeaponImages}/sceptors/Rusthandle.webp`,
    properties: [],
  },
  {
    name: "Stormeye",
    type: "sceptor",
    image: `${pathToWeaponImages}/sceptors/Stormeye.webp`,
    properties: [],
  },
  {
    name: "The Fetid Sprinkler",
    type: "sceptor",
    image: `${pathToWeaponImages}/sceptors/The_Fetid_Sprinkler.webp`,
    properties: [],
  },
  {
    name: "The Redeemer",
    type: "sceptor",
    image: `${pathToWeaponImages}/sceptors/The_Redeemer.webp`,
    properties: [],
  },
  {
    name: "Zakarum's Hand",
    type: "sceptor",
    image: `${pathToWeaponImages}/sceptors/Zakarum's_Hand.webp`,
    properties: [],
  },
  {
    name: "Arioc's Needle",
    type: "spear",
    image: `${pathToWeaponImages}/spears/Arioc's_Needle.webp`,
    properties: [],
  },
  {
    name: "Bloodthief",
    type: "spear",
    image: `${pathToWeaponImages}/spears/Bloodthief.webp`,
    properties: [],
  },
  {
    name: "Hone Sundan",
    type: "spear",
    image: `${pathToWeaponImages}/spears/Hone_Sundan.webp`,
    properties: [],
  },
  {
    name: "Kelpie Snare",
    type: "spear",
    image: `${pathToWeaponImages}/spears/Kelpie_Snare.webp`,
    properties: [],
  },
  {
    name: "Lance of Yaggai",
    type: "spear",
    image: `${pathToWeaponImages}/spears/Lance_of_Yaggai.webp`,
    properties: [],
  },
  {
    name: "Lycander's Flank",
    type: "spear",
    image: `${pathToWeaponImages}/spears/Lycander's_Flank.webp`,
    properties: [],
  },
  {
    name: "Razortine",
    type: "spear",
    image: `${pathToWeaponImages}/spears/Razortine.webp`,
    properties: [],
  },
  {
    name: "Soulfeast Tine",
    type: "spear",
    image: `${pathToWeaponImages}/spears/Soulfeast_Tine.webp`,
    properties: [],
  },
  {
    name: "Spire of Honor",
    type: "spear",
    image: `${pathToWeaponImages}/spears/Spire_of_Honor.webp`,
    properties: [],
  },
  {
    name: "Steel Pillar",
    type: "spear",
    image: `${pathToWeaponImages}/spears/Steel_Pillar.webp`,
    properties: [],
  },
  {
    name: "Stoneraven",
    type: "spear",
    image: `${pathToWeaponImages}/spears/Stoneraven.webp`,
    properties: [],
  },
  {
    name: "The Dragon Chang",
    type: "spear",
    image: `${pathToWeaponImages}/spears/The_Dragon_Chang.webp`,
    properties: [],
  },
  {
    name: "The Impaler",
    type: "spear",
    image: `${pathToWeaponImages}/spears/The_Impaler.webp`,
    properties: [],
  },
  {
    name: "The Tannr Gorerod",
    type: "spear",
    image: `${pathToWeaponImages}/spears/The_Tannr_Gorerod.webp`,
    properties: [],
  },
  {
    name: "Viperfork",
    type: "spear",
    image: `${pathToWeaponImages}/spears/Viperfork.webp`,
    properties: [],
  },
  {
    name: "Bane Ash",
    type: "staff",
    image: `${pathToWeaponImages}/staves/Bane_Ash.webp`,
    properties: [],
  },
  {
    name: "Chromatic Ire",
    type: "staff",
    image: `${pathToWeaponImages}/staves/Chromatic_Ire.webp`,
    properties: [],
  },
  {
    name: "Mang Song's Lesson",
    type: "staff",
    image: `${pathToWeaponImages}/staves/Mang_Song's_Lesson.webp`,
    properties: [],
  },
  {
    name: "Ondal's Wisdom",
    type: "staff",
    image: `${pathToWeaponImages}/staves/Ondal's_Wisdom.webp`,
    properties: [],
  },
  {
    name: "Razorswitch",
    type: "staff",
    image: `${pathToWeaponImages}/staves/Razorswitch.webp`,
    properties: [],
  },
  {
    name: "Ribcracker",
    type: "staff",
    image: `${pathToWeaponImages}/staves/Ribcracker.webp`,
    properties: [],
  },
  {
    name: "Serpent Lord",
    type: "staff",
    image: `${pathToWeaponImages}/staves/Serpent_Lord.webp`,
    properties: [],
  },
  {
    name: "Skull Collector",
    type: "staff",
    image: `${pathToWeaponImages}/staves/Skull_Collector.webp`,
    properties: [],
  },
  {
    name: "Spire of Lazarus",
    type: "staff",
    image: `${pathToWeaponImages}/staves/Spire_of_Lazarus.webp`,
    properties: [],
  },
  {
    name: "The Iron Jang Bong",
    type: "staff",
    image: `${pathToWeaponImages}/staves/The_Iron_Jang_Bong.webp`,
    properties: [],
  },
  {
    name: "The Salamander",
    type: "staff",
    image: `${pathToWeaponImages}/staves/The_Salamander.webp`,
    properties: [],
  },
  {
    name: "Warpspear",
    type: "staff",
    image: `${pathToWeaponImages}/staves/Warpspear.webp`,
    properties: [],
  },
  {
    name: "Azurewrath",
    type: "sword",
    image: `${pathToWeaponImages}/swords/Azurewrath.webp`,
    properties: [],
  },
  {
    name: "Bing Sz Wang",
    type: "sword",
    image: `${pathToWeaponImages}/swords/Bing_Sz_Wang.webp`,
    properties: [],
  },
  {
    name: "Blacktongue",
    type: "sword",
    image: `${pathToWeaponImages}/swords/Blacktongue.webp`,
    properties: [],
  },
  {
    name: "Blade of Ali Baba",
    type: "sword",
    image: `${pathToWeaponImages}/swords/Blade_of_Ali_Baba.webp`,
    properties: [],
  },
  {
    name: "Blood Crescent",
    type: "sword",
    image: `${pathToWeaponImages}/swords/Blood_Crescent.webp`,
    properties: [],
  },
  {
    name: "Bloodletter",
    type: "sword",
    image: `${pathToWeaponImages}/swords/Bloodletter.webp`,
    properties: [],
  },
  {
    name: "Bloodmoon",
    type: "sword",
    image: `${pathToWeaponImages}/swords/Bloodmoon.webp`,
    properties: [],
  },
  {
    name: "Cloudcrack",
    type: "sword",
    image: `${pathToWeaponImages}/swords/Cloudcrack.webp`,
    properties: [],
  },
  {
    name: "Coldsteel Eye",
    type: "sword",
    image: `${pathToWeaponImages}/swords/Coldsteel_Eye.webp`,
    properties: [],
  },
  {
    name: "Crainte Vomir",
    type: "sword",
    image: `${pathToWeaponImages}/swords/Crainte_Vomir.webp`,
    properties: [],
  },
  {
    name: "Culwen's Point",
    type: "sword",
    image: `${pathToWeaponImages}/swords/Culwen's_Point.webp`,
    properties: [],
  },
  {
    name: "Djinn Slayer",
    type: "sword",
    image: `${pathToWeaponImages}/swords/Djinn_Slayer.webp`,
    properties: [],
  },
  {
    name: "Doombringer",
    type: "sword",
    image: `${pathToWeaponImages}/swords/Doombringer.webp`,
    properties: [],
  },
  {
    name: "Flamebellow",
    type: "sword",
    image: `${pathToWeaponImages}/swords/Flamebellow.webp`,
    properties: [],
  },
  {
    name: "Frostwind",
    type: "sword",
    image: `${pathToWeaponImages}/swords/Frostwind.webp`,
    properties: [],
  },
  {
    name: "Ginther's Rift",
    type: "sword",
    image: `${pathToWeaponImages}/swords/Ginther's_Rift.webp`,
    properties: [],
  },
  {
    name: "Gleamscythe",
    type: "sword",
    image: `${pathToWeaponImages}/swords/Gleamscythe.webp`,
    properties: [],
  },
  {
    name: "Griswold's Edge",
    type: "sword",
    image: `${pathToWeaponImages}/swords/Griswold's_Edge.webp`,
    properties: [],
  },
  {
    name: "Headstriker",
    type: "sword",
    image: `${pathToWeaponImages}/swords/Headstriker.webp`,
    properties: [],
  },
  {
    name: "Hellplague",
    type: "sword",
    image: `${pathToWeaponImages}/swords/Hellplague.webp`,
    properties: [],
  },
  {
    name: "Hexfire",
    type: "sword",
    image: `${pathToWeaponImages}/swords/Hexfire.webp`,
    properties: [],
  },
  {
    name: "Kinemil's Awl",
    type: "sword",
    image: `${pathToWeaponImages}/swords/Kinemil's_Awl.webp`,
    properties: [],
  },
  {
    name: "Lightsabre",
    type: "sword",
    image: `${pathToWeaponImages}/swords/Lightsabre.webp`,
    properties: [],
  },
  {
    name: "Plague Bearer",
    type: "sword",
    image: `${pathToWeaponImages}/swords/Plague_Bearer.webp`,
    properties: [],
  },
  {
    name: "Ripsaw",
    type: "sword",
    image: `${pathToWeaponImages}/swords/Ripsaw.webp`,
    properties: [],
  },
  {
    name: "Rixot's Keen",
    type: "sword",
    image: `${pathToWeaponImages}/swords/Rixot's_Keen.webp`,
    properties: [],
  },
  {
    name: "Shadowfang",
    type: "sword",
    image: `${pathToWeaponImages}/swords/Shadowfang.webp`,
    properties: [],
  },
  {
    name: "Skewer of Krintiz",
    type: "sword",
    image: `${pathToWeaponImages}/swords/Skewer_of_Krintiz.webp`,
    properties: [],
  },
  {
    name: "Soulflay",
    type: "sword",
    image: `${pathToWeaponImages}/swords/Soulflay.webp`,
    properties: [],
  },
  {
    name: "Swordguard",
    type: "sword",
    image: `${pathToWeaponImages}/swords/Swordguard.webp`,
    properties: [],
  },
  {
    name: "The Atlantean",
    type: "sword",
    image: `${pathToWeaponImages}/swords/The_Atlantean.webp`,
    properties: [],
  },
  {
    name: "The Grandfather",
    type: "sword",
    image: `${pathToWeaponImages}/swords/The_Grandfather.webp`,
    properties: [],
  },
  {
    name: "The Patriarch",
    type: "sword",
    image: `${pathToWeaponImages}/swords/The_Patriarch.webp`,
    properties: [],
  },
  {
    name: "The Vile Husk",
    type: "sword",
    image: `${pathToWeaponImages}/swords/The_Vile_Husk.webp`,
    properties: [],
  },
  {
    name: "Todesfaelle Flamme",
    type: "sword",
    image: `${pathToWeaponImages}/swords/Todesfaelle_Flamme.webp`,
    properties: [],
  },
  {
    name: "Deathbit",
    type: "throwing",
    image: `${pathToWeaponImages}/throwing/Deathbit.webp`,
    properties: [],
  },
  {
    name: "Gimmershred",
    type: "throwing",
    image: `${pathToWeaponImages}/throwing/Gimmershred.webp`,
    properties: [],
  },
  {
    name: "Lacerator",
    type: "throwing",
    image: `${pathToWeaponImages}/throwing/Lacerator.webp`,
    properties: [],
  },
  {
    name: "The Scalper",
    type: "throwing",
    image: `${pathToWeaponImages}/throwing/The_Scalper.webp`,
    properties: [],
  },
  {
    name: "Warshrike",
    type: "throwing",
    image: `${pathToWeaponImages}/throwing/Warshrike.webp`,
    properties: [],
  },
  {
    name: "Arm of King Leoric",
    type: "wand",
    image: `${pathToWeaponImages}/wands/Arm_of_King_Leoric.webp`,
    properties: [],
  },
  {
    name: "Blackhand Key",
    type: "wand",
    image: `${pathToWeaponImages}/wands/Blackhand_Key.webp`,
    properties: [],
  },
  {
    name: "Boneshade",
    type: "wand",
    image: `${pathToWeaponImages}/wands/Boneshade.webp`,
    properties: [],
  },
  {
    name: "Carin Shard",
    type: "wand",
    image: `${pathToWeaponImages}/wands/Carin_Shard.webp`,
    properties: [],
  },
  {
    name: "Death's Web",
    type: "wand",
    image: `${pathToWeaponImages}/wands/Death's_Web.webp`,
    properties: [],
  },
  {
    name: "Gravenspine",
    type: "wand",
    image: `${pathToWeaponImages}/wands/Gravenspine.webp`,
    properties: [],
  },
  {
    name: "Maelstrom",
    type: "wand",
    image: `${pathToWeaponImages}/wands/Maelstrom.webp`,
    properties: [],
  },
  {
    name: "Suicide Branch",
    type: "wand",
    image: `${pathToWeaponImages}/wands/Suicide_Branch.webp`,
    properties: [],
  },
  {
    name: "Torch of Iro",
    type: "wand",
    image: `${pathToWeaponImages}/wands/Torch_of_Iro.webp`,
    properties: [],
  },
  {
    name: "Arachnid Mesh",
    type: "belt",
    image: `${pathToArmorImages}/belts/Arachnid_Mesh.webp`,
    properties: [],
  },
  {
    name: "Bladebuckle",
    type: "belt",
    image: `${pathToArmorImages}/belts/Bladebuckle.webp`,
    properties: [],
  },
  {
    name: "Gloom's Trap",
    type: "belt",
    image: `${pathToArmorImages}/belts/Gloom's_Trap.webp`,
    properties: [],
  },
  {
    name: "Lenymo",
    type: "belt",
    image: `${pathToArmorImages}/belts/Lenymo.webp`,
    properties: [],
  },
  {
    name: "Nightsmoke",
    type: "belt",
    image: `${pathToArmorImages}/belts/Nightsmoke.webp`,
    properties: [],
  },
  {
    name: "Goldwrap",
    type: "belt",
    image: `${pathToArmorImages}/belts/GoldWrap.webp`,
    properties: [],
  },
  {
    name: "Nosferatu's Coil",
    type: "belt",
    image: `${pathToArmorImages}/belts/Nosferatu's_Coil.webp`,
    properties: [],
  },
  {
    name: "Razortail",
    type: "belt",
    image: `${pathToArmorImages}/belts/Razortail.webp`,
    properties: [],
  },
  {
    name: "Snakecord",
    type: "belt",
    image: `${pathToArmorImages}/belts/Snakecord.webp`,
    properties: [],
  },
  {
    name: "Snowclash",
    type: "belt",
    image: `${pathToArmorImages}/belts/Snowclash.webp`,
    properties: [],
  },
  {
    name: "String of Ears",
    type: "belt",
    image: `${pathToArmorImages}/belts/String_of_Ears.webp`,
    properties: [],
  },
  {
    name: "Thundergod's Vigor",
    type: "belt",
    image: `${pathToArmorImages}/belts/Thundergod's_Vigor.webp`,
    properties: [],
  },
  {
    name: "Verdungo's Hearty Cord",
    type: "belt",
    image: `${pathToArmorImages}/belts/Verdungo's_Hearty_Cord.webp`,
    properties: [],
  },
  {
    name: "Goblin Toe",
    type: "boot",
    image: `${pathToArmorImages}/boots/Goblin_Toe.webp`,
    properties: [],
  },
  {
    name: "Gore Rider",
    type: "boot",
    image: `${pathToArmorImages}/boots/Gore_Rider.webp`,
    properties: [],
  },
  {
    name: "Gorefoot",
    type: "boot",
    image: `${pathToArmorImages}/boots/Gorefoot.webp`,
    properties: [],
  },
  {
    name: "Hotspur",
    type: "boot",
    image: `${pathToArmorImages}/boots/Hotspur.webp`,
    properties: [],
  },
  {
    name: "Infernostride",
    type: "boot",
    image: `${pathToArmorImages}/boots/Infernostride.webp`,
    properties: [],
  },
  {
    name: "Marrowwalk",
    type: "boot",
    image: `${pathToArmorImages}/boots/Marrowwalk.webp`,
    properties: [],
  },
  {
    name: "Sandstorm Trek",
    type: "boot",
    image: `${pathToArmorImages}/boots/Sandstorm_Trek.webp`,
    properties: [],
  },
  {
    name: "Shadow Dancer",
    type: "boot",
    image: `${pathToArmorImages}/boots/Shadow_Dancer.webp`,
    properties: [],
  },
  {
    name: "Silkweave",
    type: "boot",
    image: `${pathToArmorImages}/boots/Silkweave.webp`,
    properties: [],
  },
  {
    name: "Tearhaunch",
    type: "boot",
    image: `${pathToArmorImages}/boots/Tearhaunch.webp`,
    properties: [],
  },
  {
    name: "Treads of Cthon",
    type: "boot",
    image: `${pathToArmorImages}/boots/Treads_of_Cthon.webp`,
    properties: [],
  },
  {
    name: "War Traveler",
    type: "boot",
    image: `${pathToArmorImages}/boots/War_Traveler.webp`,
    properties: [],
  },
  {
    name: "Waterwalk",
    type: "boot",
    image: `${pathToArmorImages}/boots/Waterwalk.webp`,
    properties: [],
  },
  {
    name: "Arkaine's Valor",
    type: "armor",
    image: `${pathToArmorImages}/chest-armor/Arkaine's_Valor.webp`,
    properties: [],
  },
  {
    name: "Atma's Wail",
    type: "armor",
    image: `${pathToArmorImages}/chest-armor/Atma's_Wail.webp`,
    properties: [],
  },
  {
    name: "Black Hades",
    type: "armor",
    image: `${pathToArmorImages}/chest-armor/Black_Hades.webp`,
    properties: [],
  },
  {
    name: "Blinkbat's Form",
    type: "armor",
    image: `${pathToArmorImages}/chest-armor/Blinkbat's_Form.webp`,
    properties: [],
  },
  {
    name: "Boneflesh",
    type: "armor",
    image: `${pathToArmorImages}/chest-armor/Boneflesh.webp`,
    properties: [],
  },
  {
    name: "Corpsemourn",
    type: "armor",
    image: `${pathToArmorImages}/chest-armor/Corpsemourn.webp`,
    properties: [],
  },
  {
    name: "Crow Caw",
    type: "armor",
    image: `${pathToArmorImages}/chest-armor/Crow_Caw.webp`,
    properties: [],
  },
  {
    name: "Darkglow",
    type: "armor",
    image: `${pathToArmorImages}/chest-armor/Darkglow.webp`,
    properties: [],
  },
  {
    name: "Duriel's Shell",
    type: "armor",
    image: `${pathToArmorImages}/chest-armor/Duriel's_Shell.webp`,
    properties: [],
  },
  {
    name: "Goldskin",
    type: "armor",
    image: `${pathToArmorImages}/chest-armor/Goldskin.webp`,
    properties: [],
  },
  {
    name: "Guardian Angel",
    type: "armor",
    image: `${pathToArmorImages}/chest-armor/Guardian_Angel.webp`,
    properties: [],
  },
  {
    name: "Hawkmail",
    type: "armor",
    image: `${pathToArmorImages}/chest-armor/Hawkmail.webp`,
    properties: [],
  },
  {
    name: "Heavenly Garb",
    type: "armor",
    image: `${pathToArmorImages}/chest-armor/Heavenly_Garb.webp`,
    properties: [],
  },
  {
    name: "Iceblink",
    type: "armor",
    image: `${pathToArmorImages}/chest-armor/Iceblink.webp`,
    properties: [],
  },
  {
    name: "Iron Pelt",
    type: "armor",
    image: `${pathToArmorImages}/chest-armor/Iron_Pelt.webp`,
    properties: [],
  },
  {
    name: "Leviathan",
    type: "armor",
    image: `${pathToArmorImages}/chest-armor/Leviathan.webp`,
    properties: [],
  },
  {
    name: "Ormus' Robes",
    type: "armor",
    image: `${pathToArmorImages}/chest-armor/Ormus'_Robes.webp`,
    properties: [],
  },
  {
    name: "Que-Hegan's Wisdom",
    type: "armor",
    image: `${pathToArmorImages}/chest-armor/Que-Hegan's_Wisdom.webp`,
    properties: [],
  },
  {
    name: "Rattlecage",
    type: "armor",
    image: `${pathToArmorImages}/chest-armor/Rattlecage.webp`,
    properties: [],
  },
  {
    name: "Rockfleece",
    type: "armor",
    image: `${pathToArmorImages}/chest-armor/Rockfleece.webp`,
    properties: [],
  },
  {
    name: "Shaftstop",
    type: "armor",
    image: `${pathToArmorImages}/chest-armor/Shaftstop.webp`,
    properties: [],
  },
  {
    name: "Silks of the Victor",
    type: "armor",
    image: `${pathToArmorImages}/chest-armor/Silks_of_the_Victor.webp`,
    properties: [],
  },
  {
    name: "Skin of the Flayed One",
    type: "armor",
    image: `${pathToArmorImages}/chest-armor/Skin_of_the_Flayed_One.webp`,
    properties: [],
  },
  {
    name: "Skin of the Vipermagi",
    type: "armor",
    image: `${pathToArmorImages}/chest-armor/Skin_of_the_Vipermagi.webp`,
    properties: [],
  },
  {
    name: "Skullder's Ire",
    type: "armor",
    image: `${pathToArmorImages}/chest-armor/Skullder's_Ire.webp`,
    properties: [],
  },
  {
    name: "Sparking Mail",
    type: "armor",
    image: `${pathToArmorImages}/chest-armor/Sparking_Mail.webp`,
    properties: [],
  },
  {
    name: "Spirit Forge",
    type: "armor",
    image: `${pathToArmorImages}/chest-armor/Spirit_Forge.webp`,
    properties: [],
  },
  {
    name: "Steel Carapace",
    type: "armor",
    image: `${pathToArmorImages}/chest-armor/Steel_Carapace.webp`,
    properties: [],
  },
  {
    name: "Templar's Might",
    type: "armor",
    image: `${pathToArmorImages}/chest-armor/Templar's_Might.webp`,
    properties: [],
  },
  {
    name: "The Centurion",
    type: "armor",
    image: `${pathToArmorImages}/chest-armor/The_Centurion.webp`,
    properties: [],
  },
  {
    name: "The Gladiator's Bane",
    type: "armor",
    image: `${pathToArmorImages}/chest-armor/The_Gladiator's_Bane.webp`,
    properties: [],
  },
  {
    name: "The Spirit Shroud",
    type: "armor",
    image: `${pathToArmorImages}/chest-armor/The_Spirit_Shroud.webp`,
    properties: [],
  },
  {
    name: "Toothrow",
    type: "armor",
    image: `${pathToArmorImages}/chest-armor/Toothrow.webp`,
    properties: [],
  },
  {
    name: "Twitchthroe",
    type: "armor",
    image: `${pathToArmorImages}/chest-armor/Twitchthroe.webp`,
    properties: [],
  },
  {
    name: "Tyrael's Might",
    type: "armor",
    image: `${pathToArmorImages}/chest-armor/Tyrael's_Might.webp`,
    properties: [],
  },
  {
    name: "Venom Ward",
    type: "armor",
    image: `${pathToArmorImages}/chest-armor/Venom_Ward.webp`,
    properties: [],
  },
  {
    name: "Bloodfist",
    type: "glove",
    image: `${pathToArmorImages}/gloves/Bloodfist.webp`,
    properties: [],
  },
  {
    name: "Chance Guards",
    type: "glove",
    image: `${pathToArmorImages}/gloves/Chance_Guards.webp`,
    properties: [],
  },
  {
    name: "Dracul's Grasp",
    type: "glove",
    image: `${pathToArmorImages}/gloves/Dracul's_Grasp.webp`,
    properties: [],
  },
  {
    name: "Frostburn",
    type: "glove",
    image: `${pathToArmorImages}/gloves/Frostburn.webp`,
    properties: [],
  },
  {
    name: "Ghoulhide",
    type: "glove",
    image: `${pathToArmorImages}/gloves/Ghoulhide.webp`,
    properties: [],
  },
  {
    name: "Gravepalm",
    type: "glove",
    image: `${pathToArmorImages}/gloves/Gravepalm.webp`,
    properties: [],
  },
  {
    name: "Hellmouth",
    type: "glove",
    image: `${pathToArmorImages}/gloves/Hellmouth.webp`,
    properties: [],
  },
  {
    name: "Lava Gout",
    type: "glove",
    image: `${pathToArmorImages}/gloves/Lava_Gout.webp`,
    properties: [],
  },
  {
    name: "Magefist",
    type: "glove",
    image: `${pathToArmorImages}/gloves/Magefist.webp`,
    properties: [],
  },
  {
    name: "Soul Drainer",
    type: "glove",
    image: `${pathToArmorImages}/gloves/Soul_Drainer.webp`,
    properties: [],
  },
  {
    name: "Steelrend",
    type: "glove",
    image: `${pathToArmorImages}/gloves/Steelrend.webp`,
    properties: [],
  },
  {
    name: "The Hand of Broc",
    type: "glove",
    image: `${pathToArmorImages}/gloves/The_Hand_of_Broc.webp`,
    properties: [],
  },
  {
    name: "Venom Grip",
    type: "glove",
    image: `${pathToArmorImages}/gloves/Venom_Grip.webp`,
    properties: [],
  },
  {
    name: "Andariel's Visage",
    type: "helm",
    image: `${pathToArmorImages}/helms/Andariel's_Visage.webp`,
    properties: [],
  },
  {
    name: "Arreat's Face",
    type: "helm",
    image: `${pathToArmorImages}/helms/Arreat's_Face.webp`,
    properties: [],
  },
  {
    name: "Biggin's Bonnet",
    type: "helm",
    image: `${pathToArmorImages}/helms/Biggin's_Bonnet.webp`,
    properties: [],
  },
  {
    name: "Blackhorn's Face",
    type: "helm",
    image: `${pathToArmorImages}/helms/Blackhorn's_Face.webp`,
    properties: [],
  },
  {
    name: "Cerebus' Bite",
    type: "helm",
    image: `${pathToArmorImages}/helms/Cerebus'_Bite.webp`,
    properties: [],
  },
  {
    name: "Coil of Glory",
    type: "helm",
    image: `${pathToArmorImages}/helms/Coil_of_Glory.webp`,
    properties: [],
  },
  {
    name: "Crown of Ages",
    type: "helm",
    image: `${pathToArmorImages}/helms/Crown_of_Ages.webp`,
    properties: [],
  },
  {
    name: "Crown of Thieves",
    type: "helm",
    image: `${pathToArmorImages}/helms/Crown_of_Thieves.webp`,
    properties: [],
  },
  {
    name: "Darksight Helm",
    type: "helm",
    image: `${pathToArmorImages}/helms/Darksight_Helm.webp`,
    properties: [],
  },
  {
    name: "Demonhorn's Edge",
    type: "helm",
    image: `${pathToArmorImages}/helms/Demonhorn's_Edge.webp`,
    properties: [],
  },
  {
    name: "Duskdeep",
    type: "helm",
    image: `${pathToArmorImages}/helms/Duskdeep.webp`,
    properties: [],
  },
  {
    name: "Giant Skull",
    type: "helm",
    image: `${pathToArmorImages}/helms/Giant Skull.webp`,
    properties: [],
  },
  {
    name: "Griffon's Eye",
    type: "helm",
    image: `${pathToArmorImages}/helms/Griffon's Eye.webp`,
    properties: [],
  },
  {
    name: "Halaberd's Reign",
    type: "helm",
    image: `${pathToArmorImages}/helms/Halaberd's_Reign.webp`,
    properties: [],
  },
  {
    name: "Harlequin Crest",
    type: "helm",
    image: `${pathToArmorImages}/helms/Harlequin_Crest.webp`,
    properties: [],
  },
  {
    name: "Howltusk",
    type: "helm",
    image: `${pathToArmorImages}/helms/Howltusk.webp`,
    properties: [],
  },
  {
    name: "Jalal's Mane",
    type: "helm",
    image: `${pathToArmorImages}/helms/Jalal's_Mane.webp`,
    properties: [],
  },
  {
    name: "Nightwing's Veil",
    type: "helm",
    image: `${pathToArmorImages}/helms/Nightwing's_Veil.webp`,
    properties: [],
  },
  {
    name: "Peasant Crown",
    type: "helm",
    image: `${pathToArmorImages}/helms/Peasant_Crown.webp`,
    properties: [],
  },
  {
    name: "Ravenlore",
    type: "helm",
    image: `${pathToArmorImages}/helms/Ravenlore.webp`,
    properties: [],
  },
  {
    name: "Rockstopper",
    type: "helm",
    image: `${pathToArmorImages}/helms/Rockstopper.webp`,
    properties: [],
  },
  {
    name: "Spirit Keeper",
    type: "helm",
    image: `${pathToArmorImages}/helms/Spirit Keeper.webp`,
    properties: [],
  },
  {
    name: "Stealskull",
    type: "helm",
    image: `${pathToArmorImages}/helms/Stealskull.webp`,
    properties: [],
  },
  {
    name: "Steel Spade",
    type: "helm",
    image: `${pathToArmorImages}/helms/Steel Spade.webp`,
    properties: [],
  },
  {
    name: "Tarnhelm",
    type: "helm",
    image: `${pathToArmorImages}/helms/Tarnhelm.webp`,
    properties: [],
  },
  {
    name: "The Face of Horror",
    type: "helm",
    image: `${pathToArmorImages}/helms/The_Face_of_Horror.webp`,
    properties: [],
  },
  {
    name: "Undead Crown",
    type: "helm",
    image: `${pathToArmorImages}/helms/Undead_Crown.webp`,
    properties: [],
  },
  {
    name: "Valkyrie Wing",
    type: "helm",
    image: `${pathToArmorImages}/helms/Valkyrie_Wing.webp`,
    properties: [],
  },
  {
    name: "Vampire Gaze",
    type: "helm",
    image: `${pathToArmorImages}/helms/Vampire_Gaze.webp`,
    properties: [],
  },
  {
    name: "Veil of Steel",
    type: "helm",
    image: `${pathToArmorImages}/helms/Veil_of_Steel.webp`,
    properties: [],
  },
  {
    name: "Wolfhowl",
    type: "helm",
    image: `${pathToArmorImages}/helms/Wolfhowl.webp`,
    properties: [],
  },
  {
    name: "Wormskull",
    type: "helm",
    image: `${pathToArmorImages}/helms/Wormskull.webp`,
    properties: [],
  },
  {
    name: "Alma Negra",
    type: "shield",
    image: `${pathToArmorImages}/shields/Alma_Negra.webp`,
    properties: [],
  },
  {
    name: "Blackoak Shield",
    type: "shield",
    image: `${pathToArmorImages}/shields/Blackoak_Shield.webp`,
    properties: [],
  },
  {
    name: "Bverrit Keep",
    type: "shield",
    image: `${pathToArmorImages}/shields/Bverrit_Keep.webp`,
    properties: [],
  },
  {
    name: "Dragonscale",
    type: "shield",
    image: `${pathToArmorImages}/shields/Dragonscale.webp`,
    properties: [],
  },
  {
    name: "Gerke's Sanctuary",
    type: "shield",
    image: `${pathToArmorImages}/shields/Gerke's_Sanctuary.webp`,
    properties: [],
  },
  {
    name: "Head Hunter's Glory",
    type: "shield",
    image: `${pathToArmorImages}/shields/Head_Hunter's_Glory.webp`,
    properties: [],
  },
  {
    name: "Herald Of Zakarum",
    type: "shield",
    image: `${pathToArmorImages}/shields/Herald_Of_Zakarum.webp`,
    properties: [],
  },
  {
    name: "Lance Guard",
    type: "shield",
    image: `${pathToArmorImages}/shields/Lance_Guard.webp`,
    properties: [],
  },
  {
    name: "Lidless Wall",
    type: "shield",
    image: `${pathToArmorImages}/shields/Lidless_Wall.webp`,
    properties: [],
  },
  {
    name: "Medusa's Gaze",
    type: "shield",
    image: `${pathToArmorImages}/shields/Medusa's_Gaze.webp`,
    properties: [],
  },
  {
    name: "Moser's Blessed Circle",
    type: "shield",
    image: `${pathToArmorImages}/shields/Moser's_Blessed_Circle.webp`,
    properties: [],
  },
  {
    name: "Pelta Lunata",
    type: "shield",
    image: `${pathToArmorImages}/shields/Pelta_Lunata.webp`,
    properties: [],
  },
  {
    name: "Radament's Sphere",
    type: "shield",
    image: `${pathToArmorImages}/shields/Radament's_Sphere.webp`,
    properties: [],
  },
  {
    name: "Spike Thorn",
    type: "shield",
    image: `${pathToArmorImages}/shields/Spike_Thorn.webp`,
    properties: [],
  },
  {
    name: "Spirit Ward",
    type: "shield",
    image: `${pathToArmorImages}/shields/Spirit_Ward.webp`,
    properties: [],
  },
  {
    name: "Steelclash",
    type: "shield",
    image: `${pathToArmorImages}/shields/Steelclash.webp`,
    properties: [],
  },
  {
    name: "Stormchaser",
    type: "shield",
    image: `${pathToArmorImages}/shields/Stormchaser.webp`,
    properties: [],
  },
  {
    name: "Stormguild",
    type: "shield",
    image: `${pathToArmorImages}/shields/Stormguild.webp`,
    properties: [],
  },
  {
    name: "Stormshield",
    type: "shield",
    image: `${pathToArmorImages}/shields/Stormshield.webp`,
    properties: [],
  },
  {
    name: "Swordback Hold",
    type: "shield",
    image: `${pathToArmorImages}/shields/Swordback_Hold.webp`,
    properties: [],
  },
  {
    name: "The Ward",
    type: "shield",
    image: `${pathToArmorImages}/shields/The_Ward.webp`,
    properties: [],
  },
  {
    name: "Tiamat's Rebuke",
    type: "shield",
    image: `${pathToArmorImages}/shields/Tiamat's_Rebuke.webp`,
    properties: [],
  },
  {
    name: "Umbral Disk",
    type: "shield",
    image: `${pathToArmorImages}/shields/Umbral_Disk.webp`,
    properties: [],
  },
  {
    name: "Visceratuant",
    type: "shield",
    image: `${pathToArmorImages}/shields/Visceratuant.webp`,
    properties: [],
  },
  {
    name: "Wall of the Eyeless",
    type: "shield",
    image: `${pathToArmorImages}/shields/Wall_of_the_Eyeless.webp`,
    properties: [],
  },
  {
    name: "Boneflame",
    type: "shruken head",
    image: `${pathToArmorImages}/shrunken-heads/Boneflame.webp`,
    properties: [],
  },
  {
    name: "Darkforce Spawn",
    type: "shrunken head",
    image: `${pathToArmorImages}/shrunken-heads/Darkforce_Spawn.webp`,
    properties: [],
  },
  {
    name: "Homunculus",
    type: "shrunken head",
    image: `${pathToArmorImages}/shrunken-heads/Homunculus.webp`,
    properties: [],
  },
];

export default uniques;
