const pathToWeaponImages = 'assets/images/d2items/uniques/weapons';
// const pathToArmorImages = 'assets/images/d2items/uniques/armors';
const pathToAccessoryImages = 'assets/images/d2items/uniques/accessories';
const pathToCharmImages = 'assets/images/d2items/uniques/charms';
const pathToJewelImages = 'assets/images/d2items/uniques/jewels';

// Object Array of all the uniques in the game
const uniques = [
    {
        name: "Annihilus",
        type: "small charm",
        image: `${pathToCharmImages}/Annihilus.webp`,
        properties: [],
    },
    {
        name: "Gheed's Fortune",
        type: "grand charm",
        image: `${pathToCharmImages}/Gheed's_Fortune.webp`,
        properties: [],
    },
    {
        name: "Hellfire Torch",
        type: "large charm",
        image: `${pathToCharmImages}/Hellfire_Torch.webp`,
        properties: [],
    },
    {
        name: "Rainbow Facet",
        type: "jewel",
        image: `${pathToJewelImages}/Blue_Facet.webp`,
        properties: [],
    },
    {
        name: "Bul-Kathos' Wedding Band",
        type: "ring",
        image: `${pathToAccessoryImages}/rings/Bul-Kathos'_Wedding_Band.webp`,
        properties: [],
    },
    {
        name: "Carrion Wind",
        type: "ring",
        image: `${pathToAccessoryImages}/rings/Carrion_Wind.webp`,
        properties: [],
    },
    {
        name: "Dwarf Star",
        type: "ring",
        image: `${pathToAccessoryImages}/rings/Dwarf_Star.webp`,
        properties: [],
    },
    {
        name: "Manald Heal",
        type: "ring",
        image: `${pathToAccessoryImages}/rings/Manald_Heal.webp`,
        properties: [],
    },
    {
        name: "Nagelring",
        type: "ring",
        image: `${pathToAccessoryImages}/rings/Nagelring.webp`,
        properties: [],
    },
    {
        name: "Nature's Peace",
        type: "ring",
        image: `${pathToAccessoryImages}/rings/Nature's_Peace.webp`,
        properties: [],
    },
    {
        name: "Raven Frost",
        type: "ring",
        image: `${pathToAccessoryImages}/rings/Raven_Frost.webp`,
        properties: [],
    },
    {
        name: "Stone of Jordan",
        type: "ring",
        image: `${pathToAccessoryImages}/rings/Stone_of_Jordan.webp`,
        properties: [],
    },
    {
        name: "Wisp Projector",
        type: "ring",
        image: `${pathToAccessoryImages}/rings/Wisp_Projector.webp`,
        properties: [],
    },
    {
        name: "Atma's Scarab",
        type: "amulet",
        image: `${pathToAccessoryImages}/amulets/Atma's_Scarab.webp`,
        properties: [],
    },
    {
        name: "Crescent Moon",
        type: "amulet",
        image: `${pathToAccessoryImages}/amulets/Crescent_Moon.webp`,
        properties: [],
    },
    {
        name: "Highlord's Wrath",
        type: "amulet",
        image: `${pathToAccessoryImages}/amulets/Highlord's_Wrath.webp`,
        properties: [],
    },
    {
        name: "Mara's Kaleidoscope",
        type: "amulet",
        image: `${pathToAccessoryImages}/amulets/Mara's_Kaleidoscope.webp`,
        properties: [],
    },
    {
        name: "Metalgrid",
        type: "amulet",
        image: `${pathToAccessoryImages}/amulets/Metalgrid.webp`,
        properties: [],
    },
    {
        name: "Nokozan Relic",
        type: "amulet",
        image: `${pathToAccessoryImages}/amulets/Nokozan_Relic.webp`,
        properties: [],
    },
    {
        name: "Saracen's Chance",
        type: "amulet",
        image: `${pathToAccessoryImages}/amulets/Saracen's_Chance.webp`,
        properties: [],
    },
    {
        name: "Seraph's Hymn",
        type: "amulet",
        image: `${pathToAccessoryImages}/amulets/Saracen's_Hymn.webp`,
        properties: [],
    },
    {
        name: "The Cat's Eye",
        type: "amulet",
        image: `${pathToAccessoryImages}/amulets/The_Cat's_Eye.webp`,
        properties: [],
    },
    {
        name: "The Eye of Etlich",
        type: "amulet",
        image: `${pathToAccessoryImages}/amulets/The_Eye_of_Etlich.webp`,
        properties: [],
    },
    {
        name: "The Mahim-Oak Curio",
        type: "amulet",
        image: `${pathToAccessoryImages}/amulets/The_Mahim-Oak_Curio.webp`,
        properties: [],
    },
    {
        name: "The Rising Sun",
        type: "amulet",
        image: `${pathToAccessoryImages}/amulets/The_Rising_Sun.webp`,
        properties: [],
    },
    {
        name: "Axe of Fechmar",
        type: "axe",
        image: `${pathToWeaponImages}/axes/Axe_of_Fechmar.webp`,
        properties: [],
    },
    {
        name: "Bladebone",
        type: "axe",
        image: `${pathToWeaponImages}/axes/Bladebone.webp`,
        properties: [],
    },
    {
        name: "Boneslayer Blade",
        type: "axe",
        image: `${pathToWeaponImages}/axes/Boneslayer_Blade.webp`,
        properties: [],
    },
    {
        name: "Brainhew",
        type: "axe",
        image: `${pathToWeaponImages}/axes/Brainhew.webp`,
        properties: [],
    },
    {
        name: "Butcher's Pupil",
        type: "axe",
        image: `${pathToWeaponImages}/axes/Butcher's_Pupil.webp`,
        properties: [],
    },
    {
        name: "Coldkill",
        type: "axe",
        image: `${pathToWeaponImages}/axes/Coldkill.webp`,
        properties: [],
    },
    {
        name: "Cranebeak",
        type: "axe",
        image: `${pathToWeaponImages}/axes/Cranebeak.webp`,
        properties: [],
    },
    {
        name: "Death Cleaver",
        type: "axe",
        image: `${pathToWeaponImages}/axes/Death_Cleaver.webp`,
        properties: [],
    },
    {
        name: "Deathspade",
        type: "axe",
        image: `${pathToWeaponImages}/axes/Deathspade.webp`,
        properties: [],
    },
    {
        name: "Ethereal Edge",
        type: "axe",
        image: `${pathToWeaponImages}/axes/Ethereal_Edge.webp`,
        properties: [],
    },
    {
        name: "Executioner's Justice",
        type: "axe",
        image: `${pathToWeaponImages}/axes/Executioner's_Justice.webp`,
        properties: [],
    },
    {
        name: "Goreshovel",
        type: "axe",
        image: `${pathToWeaponImages}/axes/Goreshovel.webp`,
        properties: [],
    },
    {
        name: "Guardian Naga",
        type: "axe",
        image: `${pathToWeaponImages}/axes/Guardian_Naga.webp`,
        properties: [],
    },
    {
        name: "Hellslayer",
        type: "axe",
        image: `${pathToWeaponImages}/axes/Hellslayer.webp`,
        properties: [],
    },
    {
        name: "Humongous",
        type: "axe",
        image: `${pathToWeaponImages}/axes/Humongous.webp`,
        properties: [],
    },
    {
        name: "Islestrike",
        type: "axe",
        image: `${pathToWeaponImages}/axes/Islestrike.webp`,
        properties: [],
    },
    {
        name: "Messerchmidt's Reaver",
        type: "axe",
        image: `${pathToWeaponImages}/axes/Messerchmidt's_Reaver.webp`,
        properties: [],
    },
    {
        name: "Pompeii's Wrath",
        type: "axe",
        image: `${pathToWeaponImages}/axes/Pompeii's_Wrath.webp`,
        properties: [],
    },
    {
        name: "Rakescar",
        type: "axe",
        image: `${pathToWeaponImages}/axes/Rakescar.webp`,
        properties: [],
    },
    {
        name: "Razor's Edge",
        type: "axe",
        image: `${pathToWeaponImages}/axes/Razor's_Edge.webp`,
        properties: [],
    },
    {
        name: "Rune Master",
        type: "axe",
        image: `${pathToWeaponImages}/axes/Rune_Master.webp`,
        properties: [],
    },
    {
        name: "Skull Splitter",
        type: "axe",
        image: `${pathToWeaponImages}/axes/Skull_Splitter.webp`,
        properties: [],
    },
    {
        name: "Spellsteel",
        type: "axe",
        image: `${pathToWeaponImages}/axes/Spellsteel.webp`,
        properties: [],
    },
    {
        name: "Stormrider",
        type: "axe",
        image: `${pathToWeaponImages}/axes/Stormrider.webp`,
        properties: [],
    },
    {
        name: "The Chieftain",
        type: "axe",
        image: `${pathToWeaponImages}/axes/The_Chieftain.webp`,
        properties: [],
    },
    {
        name: "The Gnasher",
        type: "axe",
        image: `${pathToWeaponImages}/axes/The_Gnasher.webp`,
        properties: [],
    },
    {
        name: "The Minotaur",
        type: "axe",
        image: `${pathToWeaponImages}/axes/The_Minotaur.webp`,
        properties: [],
    },
    {
        name: "Warlord's Trust",
        type: "axe",
        image: `${pathToWeaponImages}/axes/Warlord's_Trust.webp`,
        properties: [],
    },
    {
        name: "Blastbark",
        type: "bow",
        image: `${pathToWeaponImages}/bows/Blastbark.webp`,
        properties: [],
    },
    {
        name: "Cliffkiller",
        type: "bow",
        image: `${pathToWeaponImages}/bows/Cliffkiller.webp`,
        properties: [],
    },
    {
        name: "Eaglehorn",
        type: "bow",
        image: `${pathToWeaponImages}/bows/Eaglehorn.webp`,
        properties: [],
    },
    {
        name: "Endlesshail",
        type: "bow",
        image: `${pathToWeaponImages}/bows/Endlesshail.webp`,
        properties: [],
    },
    {
        name: "Goldstrike Arch",
        type: "bow",
        image: `${pathToWeaponImages}/bows/Goldstrike_Arch.webp`,
        properties: [],
    },
    {
        name: "Hellclap",
        type: "bow",
        image: `${pathToWeaponImages}/bows/Hellclap.webp`,
        properties: [],
    },
    {
        name: "Kuko Shukaku",
        type: "bow",
        image: `${pathToWeaponImages}/bows/Kuko_Shukaku.webp`,
        properties: [],
    },
    {
        name: "Magewrath",
        type: "bow",
        image: `${pathToWeaponImages}/bows/Magewrath.webp`,
        properties: [],
    },
    {
        name: "Pluckeye",
        type: "bow",
        image: `${pathToWeaponImages}/bows/Pluckeye.webp`,
        properties: [],
    },
    {
        name: "Raven Claw",
        type: "bow",
        image: `${pathToWeaponImages}/bows/Raven_Claw.webp`,
        properties: [],
    },
    {
        name: "Riphook",
        type: "bow",
        image: `${pathToWeaponImages}/bows/Riphook.webp`,
        properties: [],
    },
    {
        name: "Rogue's Bow",
        type: "bow",
        image: `${pathToWeaponImages}/bows/Rogue's_Bow.webp`,
        properties: [],
    },
    {
        name: "Skystrike",
        type: "bow",
        image: `${pathToWeaponImages}/bows/Skystrike.webp`,
        properties: [],
    },
    {
        name: "Stormstrike",
        type: "bow",
        image: `${pathToWeaponImages}/bows/Stormstrike.webp`,
        properties: [],
    },
    {
        name: "Widowmaker",
        type: "bow",
        image: `${pathToWeaponImages}/bows/Widowmaker.webp`,
        properties: [],
    },
    {
        name: "Windforce",
        type: "bow",
        image: `${pathToWeaponImages}/bows/Windforce.webp`,
        properties: [],
    },
    {
        name: "Witchwild String",
        type: "bow",
        image: `${pathToWeaponImages}/bows/Witchwild_String.webp`,
        properties: [],
    },
    {
        name: "Witherspring",
        type: "bow",
        image: `${pathToWeaponImages}/bows/Witherspring.webp`,
        properties: [],
    },
    {
        name: "Wizendraw",
        type: "bow",
        image: `${pathToWeaponImages}/bows/Wizendraw.webp`,
        properties: [],
    },
    {
        name: "Dark Clan Crusher",
        type: "club",
        image: `${pathToWeaponImages}/clubs/Dark_Clan_Crusher.webp`,
        properties: [],
    },
    {
        name: "Demon Limb",
        type: "club",
        image: `${pathToWeaponImages}/clubs/Demon_Limb.webp`,
        properties: [],
    },
    {
        name: "Felloak",
        type: "club",
        image: `${pathToWeaponImages}/clubs/Felloak.webp`,
        properties: [],
    },
    {
        name: "Fleshrender",
        type: "club",
        image: `${pathToWeaponImages}/clubs/Fleshrender.webp`,
        properties: [],
    },
    {
        name: "Nord's Tenderizer",
        type: "club",
        image: `${pathToWeaponImages}/clubs/Nord's_Tenderizer.webp`,
        properties: [],
    },
    {
        name: "Stoutnail",
        type: "club",
        image: `${pathToWeaponImages}/clubs/Stoutnail.webp`,
        properties: [],
    },
    {
        name: "Buriza-Do Kyanon",
        type: "crossbow",
        image: `${pathToWeaponImages}/crossbows/Buriza-Do_Kyanon.webp`,
        properties: [],
    },
    {
        name: "Demon Machine",
        type: "crossbow",
        image: `${pathToWeaponImages}/crossbows/Demon_Machine.webp`,
        properties: [],
    },
    {
        name: "Doomslinger",
        type: "crossbow",
        image: `${pathToWeaponImages}/crossbows/Doomslinger.webp`,
        properties: [],
    },
    {
        name: "Gut Siphon",
        type: "crossbow",
        image: `${pathToWeaponImages}/crossbows/Gut_Siphon.webp`,
        properties: [],
    },
    {
        name: "Hellcast",
        type: "crossbow",
        image: `${pathToWeaponImages}/crossbows/Hellcast.webp`,
        properties: [],
    },
    {
        name: "Hellrack",
        type: "crossbow",
        image: `${pathToWeaponImages}/crossbows/Hellrack.webp`,
        properties: [],
    },
    {
        name: "Ichorstring",
        type: "crossbow",
        image: `${pathToWeaponImages}/crossbows/Ichorstring.webp`,
        properties: [],
    },
    {
        name: "Langer Briser",
        type: "crossbow",
        image: `${pathToWeaponImages}/crossbows/Langer_Briser.webp`,
        properties: [],
    },
    {
        name: "Leadcrow",
        type: "crossbow",
        image: `${pathToWeaponImages}/crossbows/Leadcrow.webp`,
        properties: [],
    },
    {
        name: "Pus Spitter",
        type: "crossbow",
        image: `${pathToWeaponImages}/crossbows/Pus_Spitter.webp`,
        properties: [],
    },
    {
        name: "Blackdog's Sharp",
        type: "dagger",
        image: `${pathToWeaponImages}/daggers/Blackdog's_Sharp.webp`,
        properties: [],
    },
    {
        name: "Fleshripper",
        type: "dagger",
        image: `${pathToWeaponImages}/daggers/Fleshripper.webp`,
        properties: [],
    },
    {
        name: "Ghostflame",
        type: "dagger",
        image: `${pathToWeaponImages}/daggers/Ghostflame.webp`,
        properties: [],
    },
    {
        name: "Gull",
        type: "dagger",
        image: `${pathToWeaponImages}/daggers/Gull.webp`,
        properties: [],
    },
    {
        name: "Heart Carver",
        type: "dagger",
        image: `${pathToWeaponImages}/daggers/Heart_Carver.webp`,
        properties: [],
    },
    {
        name: "Spectral Shard",
        type: "dagger",
        image: `${pathToWeaponImages}/daggers/Spectral_Shard.webp`,
        properties: [],
    },
    {
        name: "Spineripper",
        type: "dagger",
        image: `${pathToWeaponImages}/daggers/Spineripper.webp`,
        properties: [],
    },
    {
        name: "Stormspike",
        type: "dagger",
        image: `${pathToWeaponImages}/daggers/Stormspike.webp`,
        properties: [],
    },
    {
        name: "The Diggler",
        type: "dagger",
        image: `${pathToWeaponImages}/daggers/The_Diggler.webp`,
        properties: [],
    },
    {
        name: "The Jade Tan Do",
        type: "dagger",
        image: `${pathToWeaponImages}/daggers/The_Jade_Tan_Do.webp`,
        properties: [],
    },
    {
        name: "Wizardspike",
        type: "dagger",
        image: `${pathToWeaponImages}/daggers/Wizardspike.webp`,
        properties: [],
    },
    {
        name: "Bloodtree Stump",
        type: "hammer",
        image: `${pathToWeaponImages}/hammers/Bloodtree_Stump.webp`,
        properties: [],
    },
    {
        name: "Bonesnap",
        type: "hammer",
        image: `${pathToWeaponImages}/hammers/Bonesnap.webp`,
        properties: [],
    },
    {
        name: "Earth Shifter",
        type: "hammer",
        image: `${pathToWeaponImages}/hammers/Earth_Shifter.webp`,
        properties: [],
    },
    {
        name: "Earthshaker",
        type: "hammer",
        image: `${pathToWeaponImages}/hammers/Earthshaker.webp`,
        properties: [],
    },
    {
        name: "Ironstone",
        type: "hammer",
        image: `${pathToWeaponImages}/hammers/Ironstone.webp`,
        properties: [],
    },
    {
        name: "Schaefer's Hammer",
        type: "hammer",
        image: `${pathToWeaponImages}/hammers/Schaefer's_Hammer.webp`,
        properties: [],
    },
    {
        name: "Steeldriver",
        type: "hammer",
        image: `${pathToWeaponImages}/hammers/Steeldriver.webp`,
        properties: [],
    },
    {
        name: "Stone Crusher",
        type: "hammer",
        image: `${pathToWeaponImages}/hammers/Stone_Crusher.webp`,
        properties: [],
    },
    {
        name: "The Cranium Basher",
        type: "hammer",
        image: `${pathToWeaponImages}/hammers/The_Cranium_Basher.webp`,
        properties: [],
    },
    {
        name: "The Gavel of Pain",
        type: "hammer",
        image: `${pathToWeaponImages}/hammers/The_Gavel_of_Pain.webp`,
        properties: [],
    },
    {
        name: "Windhammer",
        type: "hammer",
        image: `${pathToWeaponImages}/hammers/Windhammer.webp`,
        properties: [],
    },
    {
        name: "Demon's Arch",
        type: "javalin",
        image: `${pathToWeaponImages}/javalins/Demon's_Arch.webp`,
        properties: [],
    },
    {
        name: "Gargoyle's Bite",
        type: "javalin",
        image: `${pathToWeaponImages}/javalins/Gargoyle's_Bite.webp`,
        properties: [],
    },
    {
        name: "Thunderstroke",
        type: "javalin",
        image: `${pathToWeaponImages}/javalins/Thunderstroke.webp`,
        properties: [],
    },
    {
        name: "Titan's Revenge",
        type: "javalin",
        image: `${pathToWeaponImages}/javalins/Titan's_Revenge.webp`,
        properties: [],
    },
    {
        name: "Wraith Flight",
        type: "javalin",
        image: `${pathToWeaponImages}/javalins/Wraith_Flight.webp`,
        properties: [],
    },
    {
        name: "Bartuc's Cut-Throat",
        type: "katar",
        image: `${pathToWeaponImages}/katars/Bartuc's_Cut-Throat.webp`,
        properties: [],
    },
    {
        name: "Firelizard's Talons",
        type: "katar",
        image: `${pathToWeaponImages}/katars/Firelizard's_Talons.webp`,
        properties: [],
    },
    {
        name: "Jade Talons",
        type: "katar",
        image: `${pathToWeaponImages}/katars/Jade_Talons.webp`,
        properties: [],
    },
    {
        name: "Shadow Killer",
        type: "katar",
        image: `${pathToWeaponImages}/katars/Shadow_Killer.webp`,
        properties: [],
    },
    {
        name: "Baezil's Vortex",
        type: "mace",
        image: `${pathToWeaponImages}/maces/Baezil's_Vortex.webp`,
        properties: [],
    },
    {
        name: "Baranar's Star",
        type: "mace",
        image: `${pathToWeaponImages}/maces/Baranar's_Star.webp`,
        properties: [],
    },
    {
        name: "Bloodrise",
        type: "mace",
        image: `${pathToWeaponImages}/maces/Bloodrise.webp`,
        properties: [],
    },
    {
        name: "Crushflange",
        type: "mace",
        image: `${pathToWeaponImages}/maces/Crushflange.webp`,
        properties: [],
    },
    {
        name: "Horizon's Tornado",
        type: "mace",
        image: `${pathToWeaponImages}/maces/Horizon's_Tornado.webp`,
        properties: [],
    },
    {
        name: "Moonfall",
        type: "mace",
        image: `${pathToWeaponImages}/maces/Moonfall.webp`,
        properties: [],
    },
    {
        name: "Stormlash",
        type: "mace",
        image: `${pathToWeaponImages}/maces/Stormlash.webp`,
        properties: [],
    },
    {
        name: "Sureshrill Frost",
        type: "mace",
        image: `${pathToWeaponImages}/maces/Sureshrill_Frost.webp`,
        properties: [],
    },
    {
        name: "The General's Tan Do Li Ga",
        type: "mace",
        image: `${pathToWeaponImages}/maces/The_General's_Tan_Do_Li_Ga.webp`,
        properties: [],
    },
    {
        name: "Death's Fathom",
        type: "orb",
        image: `${pathToWeaponImages}/orbs/Death's_Fathom.webp`,
        properties: [],
    },
    {
        name: "Eschuta's Temper",
        type: "orb",
        image: `${pathToWeaponImages}/orbs/Eschuta's_Temper.webp`,
        properties: [],
    },
    {
        name: "The Oculus",
        type: "orb",
        image: `${pathToWeaponImages}/orbs/The_Oculus.webp`,
        properties: [],
    },
    {
        name: "Athena's Wrath",
        type: "polearm",
        image: `${pathToWeaponImages}/polearms/Athena's_Wrath.webp`,
        properties: [],
    },
    {
        name: "Blackreach Blade",
        type: "polearm",
        image: `${pathToWeaponImages}/polearms/Blackreach_Blade.webp`,
        properties: [],
    },
    {
        name: "Bonehew",
        type: "polearm",
        image: `${pathToWeaponImages}/polearms/Bonehew.webp`,
        properties: [],
    },
    {
        name: "Dimoak's Hew",
        type: "polearm",
        image: `${pathToWeaponImages}/polearms/Dimoak's_Hew.webp`,
        properties: [],
    },
    {
        name: "Grim's Burning Dead",
        type: "polearm",
        image: `${pathToWeaponImages}/polearms/Grim's_Burning_Dead.webp`,
        properties: [],
    },
    {
        name: "Husoldal Evo",
        type: "polearm",
        image: `${pathToWeaponImages}/polearms/Husoldal_Evo.webp`,
        properties: [],
    },
    {
        name: "Pierre Tombale Couant",
        type: "polearm",
        image: `${pathToWeaponImages}/polearms/Pierre_Tombale_Couant.webp`,
        properties: [],
    },
    {
        name: "Soul Harvest",
        type: "polearm",
        image: `${pathToWeaponImages}/polearms/Soul_Harvest.webp`,
        properties: [],
    },
    {
        name: "Steelgoad",
        type: "polearm",
        image: `${pathToWeaponImages}/polearms/Steelgoad.webp`,
        properties: [],
    },
    {
        name: "Stormspire",
        type: "polearm",
        image: `${pathToWeaponImages}/polearms/Stormspire.webp`,
        properties: [],
    },
    {
        name: "The Battlebranch",
        type: "polearm",
        image: `${pathToWeaponImages}/polearms/The_Battlebranch.webp`,
        properties: [],
    },
    {
        name: "The Grim Reaper",
        type: "polearm",
        image: `${pathToWeaponImages}/polearms/The_Grim_Reaper.webp`,
        properties: [],
    },
    {
        name: "The Meat Scrapper",
        type: "polearm",
        image: `${pathToWeaponImages}/polearms/The_Meat_Scrapper.webp`,
        properties: [],
    },
    {
        name: "The Reaper's Toll",
        type: "polearm",
        image: `${pathToWeaponImages}/polearms/The_Reaper's_Toll.webp`,
        properties: [],
    },
    {
        name: "Tomb Reaver",
        type: "polearm",
        image: `${pathToWeaponImages}/polearms/Tomb_Reaver.webp`,
        properties: [],
    },
    {
        name: "Woestave",
        type: "polearm",
        image: `${pathToWeaponImages}/polearms/Woestave.webp`,
        properties: [],
    },
    {
        name: "Astreon's Iron Ward",
        type: "sceptor",
        image: `${pathToWeaponImages}/sceptors/Astreon's_Iron_Ward.webp`,
        properties: [],
    },
    {
        name: "Hand of Blessed Light",
        type: "sceptor",
        image: `${pathToWeaponImages}/sceptors/Hand_of_Blessed_Light.webp`,
        properties: [],
    },
    {
        name: "Heaven's Light",
        type: "sceptor",
        image: `${pathToWeaponImages}/sceptors/Heaven's_Light.webp`,
        properties: [],
    },
    {
        name: "Knell Striker",
        type: "sceptor",
        image: `${pathToWeaponImages}/sceptors/Knell_Striker.webp`,
        properties: [],
    },
    {
        name: "Rusthandle",
        type: "sceptor",
        image: `${pathToWeaponImages}/sceptors/Rusthandle.webp`,
        properties: [],
    },
    {
        name: "Stormeye",
        type: "sceptor",
        image: `${pathToWeaponImages}/sceptors/Stormeye.webp`,
        properties: [],
    },
    {
        name: "The Fetid Sprinkler",
        type: "sceptor",
        image: `${pathToWeaponImages}/sceptors/The_Fetid_Sprinkler.webp`,
        properties: [],
    },
    {
        name: "The Redeemer",
        type: "sceptor",
        image: `${pathToWeaponImages}/sceptors/The_Redeemer.webp`,
        properties: [],
    },
    {
        name: "Zakarum's Hand",
        type: "sceptor",
        image: `${pathToWeaponImages}/sceptors/Zakarum's_Hand.webp`,
        properties: [],
    },
    {
        name: "Arioc's Needle",
        type: "spear",
        image: `${pathToWeaponImages}/spears/Arioc's_Needle.webp`,
        properties: [],
    },
    {
        name: "Bloodthief",
        type: "spear",
        image: `${pathToWeaponImages}/spears/Bloodthief.webp`,
        properties: [],
    },
    {
        name: "Hone Sundan",
        type: "spear",
        image: `${pathToWeaponImages}/spears/Hone_Sundan.webp`,
        properties: [],
    },
    {
        name: "Kelpie Snare",
        type: "spear",
        image: `${pathToWeaponImages}/spears/Kelpie_Snare.webp`,
        properties: [],
    },
    {
        name: "Lance of Yaggai",
        type: "spear",
        image: `${pathToWeaponImages}/spears/Lance_of_Yaggai.webp`,
        properties: [],
    },
    {
        name: "Lycander's Flank",
        type: "spear",
        image: `${pathToWeaponImages}/spears/Lycander's_Flank.webp`,
        properties: [],
    },
    {
        name: "Razortine",
        type: "spear",
        image: `${pathToWeaponImages}/spears/Razortine.webp`,
        properties: [],
    },
    {
        name: "Soulfeast Tine",
        type: "spear",
        image: `${pathToWeaponImages}/spears/Soulfeast_Tine.webp`,
        properties: [],
    },
    {
        name: "Spire of Honor",
        type: "spear",
        image: `${pathToWeaponImages}/spears/Spire_of_Honor.webp`,
        properties: [],
    },
    {
        name: "Steel Pillar",
        type: "spear",
        image: `${pathToWeaponImages}/spears/Steel_Pillar.webp`,
        properties: [],
    },
    {
        name: "Stoneraven",
        type: "spear",
        image: `${pathToWeaponImages}/spears/Stoneraven.webp`,
        properties: [],
    },
    {
        name: "The Dragon Chang",
        type: "spear",
        image: `${pathToWeaponImages}/spears/The_Dragon_Chang.webp`,
        properties: [],
    },
    {
        name: "The Impaler",
        type: "spear",
        image: `${pathToWeaponImages}/spears/The_Impaler.webp`,
        properties: [],
    },
    {
        name: "The Tannr Gorerod",
        type: "spear",
        image: `${pathToWeaponImages}/spears/The_Tannr_Gorerod.webp`,
        properties: [],
    },
    {
        name: "Viperfork",
        type: "spear",
        image: `${pathToWeaponImages}/spears/Viperfork.webp`,
        properties: [],
    },
    {
        name: "Bane Ash",
        type: "staff",
        image: `${pathToWeaponImages}/staves/Bane_Ash.webp`,
        properties: [],
    },
    {
        name: "Chromatic Ire",
        type: "staff",
        image: `${pathToWeaponImages}/staves/Chromatic_Ire.webp`,
        properties: [],
    },
    {
        name: "Mang Song's Lesson",
        type: "staff",
        image: `${pathToWeaponImages}/staves/Mang_Song's_Lesson.webp`,
        properties: [],
    },
    {
        name: "Ondal's Wisdom",
        type: "staff",
        image: `${pathToWeaponImages}/staves/Ondal's_Wisdom.webp`,
        properties: [],
    },
    {
        name: "Razorswitch",
        type: "staff",
        image: `${pathToWeaponImages}/staves/Razorswitch.webp`,
        properties: [],
    },
    {
        name: "Ribcracker",
        type: "staff",
        image: `${pathToWeaponImages}/staves/Ribcracker.webp`,
        properties: [],
    },
    {
        name: "Serpent Lord",
        type: "staff",
        image: `${pathToWeaponImages}/staves/Serpent_Lord.webp`,
        properties: [],
    },
    {
        name: "Skull Collector",
        type: "staff",
        image: `${pathToWeaponImages}/staves/Skull_Collector.webp`,
        properties: [],
    },
    {
        name: "Spire of Lazarus",
        type: "staff",
        image: `${pathToWeaponImages}/staves/Spire_of_Lazarus.webp`,
        properties: [],
    },
    {
        name: "The Iron Jang Bong",
        type: "staff",
        image: `${pathToWeaponImages}/staves/The_Iron_Jang_Bong.webp`,
        properties: [],
    },
    {
        name: "The Salamander",
        type: "staff",
        image: `${pathToWeaponImages}/staves/The_Salamander.webp`,
        properties: [],
    },
    {
        name: "Warpspear",
        type: "staff",
        image: `${pathToWeaponImages}/staves/Warpspear.webp`,
        properties: [],
    },
    {
        name: "Azurewrath",
        type: "sword",
        image: `${pathToWeaponImages}/swords/Azurewrath.webp`,
        properties: [],
    },
    {
        name: "Bing Sz Wang",
        type: "sword",
        image: `${pathToWeaponImages}/swords/Bing_Sz_Wang.webp`,
        properties: [],
    },
    {
        name: "Blacktongue",
        type: "sword",
        image: `${pathToWeaponImages}/swords/Blacktongue.webp`,
        properties: [],
    },
    {
        name: "Blade of Ali Baba",
        type: "sword",
        image: `${pathToWeaponImages}/swords/Blade_of_Ali_Baba.webp`,
        properties: [],
    },
    {
        name: "Blood Crescent",
        type: "sword",
        image: `${pathToWeaponImages}/swords/Blood_Crescent.webp`,
        properties: [],
    },
    {
        name: "Bloodletter",
        type: "sword",
        image: `${pathToWeaponImages}/swords/Bloodletter.webp`,
        properties: [],
    },
    {
        name: "Bloodmoon",
        type: "sword",
        image: `${pathToWeaponImages}/swords/Bloodmoon.webp`,
        properties: [],
    },
    {
        name: "Cloudcrack",
        type: "sword",
        image: `${pathToWeaponImages}/swords/Cloudcrack.webp`,
        properties: [],
    },
    {
        name: "Coldsteel Eye",
        type: "sword",
        image: `${pathToWeaponImages}/swords/Coldsteel_Eye.webp`,
        properties: [],
    },
    {
        name: "Crainte Vomir",
        type: "sword",
        image: `${pathToWeaponImages}/swords/Crainte_Vomir.webp`,
        properties: [],
    },
    {
        name: "Culwen's Point",
        type: "sword",
        image: `${pathToWeaponImages}/swords/Culwen's_Point.webp`,
        properties: [],
    },
    {
        name: "Djinn Slayer",
        type: "sword",
        image: `${pathToWeaponImages}/swords/Djinn_Slayer.webp`,
        properties: [],
    },
    {
        name: "Doombringer",
        type: "sword",
        image: `${pathToWeaponImages}/swords/Doombringer.webp`,
        properties: [],
    },
    {
        name: "Flamebellow",
        type: "sword",
        image: `${pathToWeaponImages}/swords/Flamebellow.webp`,
        properties: [],
    },
    {
        name: "Frostwind",
        type: "sword",
        image: `${pathToWeaponImages}/swords/Frostwind.webp`,
        properties: [],
    },
    {
        name: "Ginther's Rift",
        type: "sword",
        image: `${pathToWeaponImages}/swords/Ginther's_Rift.webp`,
        properties: [],
    },
    {
        name: "Gleamscythe",
        type: "sword",
        image: `${pathToWeaponImages}/swords/Gleamscythe.webp`,
        properties: [],
    },
    {
        name: "Griswold's Edge",
        type: "sword",
        image: `${pathToWeaponImages}/swords/Griswold's_Edge.webp`,
        properties: [],
    },
    {
        name: "Headstriker",
        type: "sword",
        image: `${pathToWeaponImages}/swords/Headstriker.webp`,
        properties: [],
    },
    {
        name: "Hellplague",
        type: "sword",
        image: `${pathToWeaponImages}/swords/Hellplague.webp`,
        properties: [],
    },
    {
        name: "Hexfire",
        type: "sword",
        image: `${pathToWeaponImages}/swords/Hexfire.webp`,
        properties: [],
    },
    {
        name: "Kinemil's Awl",
        type: "sword",
        image: `${pathToWeaponImages}/swords/Kinemil's_Awl.webp`,
        properties: [],
    },
    {
        name: "Lightsabre",
        type: "sword",
        image: `${pathToWeaponImages}/swords/Lightsabre.webp`,
        properties: [],
    },
    {
        name: "Plague Bearer",
        type: "sword",
        image: `${pathToWeaponImages}/swords/Plague_Bearer.webp`,
        properties: [],
    },
    {
        name: "Ripsaw",
        type: "sword",
        image: `${pathToWeaponImages}/swords/Ripsaw.webp`,
        properties: [],
    },
    {
        name: "Rixot's Keen",
        type: "sword",
        image: `${pathToWeaponImages}/swords/Rixot's_Keen.webp`,
        properties: [],
    },
    {
        name: "Shadowfang",
        type: "sword",
        image: `${pathToWeaponImages}/swords/Shadowfang.webp`,
        properties: [],
    },
    {
        name: "Skewer of Krintiz",
        type: "sword",
        image: `${pathToWeaponImages}/swords/Skewer_of_Krintiz.webp`,
        properties: [],
    },
    {
        name: "Soulflay",
        type: "sword",
        image: `${pathToWeaponImages}/swords/Soulflay.webp`,
        properties: [],
    },
    {
        name: "Swordguard",
        type: "sword",
        image: `${pathToWeaponImages}/swords/Swordguard.webp`,
        properties: [],
    },
    {
        name: "The Atlantean",
        type: "sword",
        image: `${pathToWeaponImages}/swords/The_Atlantean.webp`,
        properties: [],
    },
    {
        name: "The Grandfather",
        type: "sword",
        image: `${pathToWeaponImages}/swords/The_Grandfather.webp`,
        properties: [],
    },
    {
        name: "The Patriarch",
        type: "sword",
        image: `${pathToWeaponImages}/swords/The_Patriarch.webp`,
        properties: [],
    },
    {
        name: "The Vile Husk",
        type: "sword",
        image: `${pathToWeaponImages}/swords/The_Vile_Husk.webp`,
        properties: [],
    },
    {
        name: "Todesfaelle Flamme",
        type: "sword",
        image: `${pathToWeaponImages}/swords/Todesfaelle_Flamme.webp`,
        properties: [],
    },
    {
        name: "Deathbit",
        type: "throwing",
        image: `${pathToWeaponImages}/throwing/Deathbit.webp`,
        properties: [],
    },
    {
        name: "Gimmershred",
        type: "throwing",
        image: `${pathToWeaponImages}/throwing/Gimmershred.webp`,
        properties: [],
    },
    {
        name: "Lacerator",
        type: "throwing",
        image: `${pathToWeaponImages}/throwing/Lacerator.webp`,
        properties: [],
    },
    {
        name: "The Scalper",
        type: "throwing",
        image: `${pathToWeaponImages}/throwing/The_Scalper.webp`,
        properties: [],
    },
    {
        name: "Warshrike",
        type: "throwing",
        image: `${pathToWeaponImages}/throwing/Warshrike.webp`,
        properties: [],
    },
    {
        name: "Arm of King Leoric",
        type: "wand",
        image: `${pathToWeaponImages}/wands/Arm_of_King_Leoric.webp`,
        properties: [],
    },
    {
        name: "Blackhand Key",
        type: "wand",
        image: `${pathToWeaponImages}/wands/Blackhand_Key.webp`,
        properties: [],
    },
    {
        name: "Boneshade",
        type: "wand",
        image: `${pathToWeaponImages}/wands/Boneshade.webp`,
        properties: [],
    },
    {
        name: "Carin Shard",
        type: "wand",
        image: `${pathToWeaponImages}/wands/Carin_Shard.webp`,
        properties: [],
    },
    {
        name: "Death's Web",
        type: "wand",
        image: `${pathToWeaponImages}/wands/Death's_Web.webp`,
        properties: [],
    },
    {
        name: "Gravenspine",
        type: "wand",
        image: `${pathToWeaponImages}/wands/Gravenspine.webp`,
        properties: [],
    },
    {
        name: "Maelstrom",
        type: "wand",
        image: `${pathToWeaponImages}/wands/Maelstrom.webp`,
        properties: [],
    },
    {
        name: "Suicide Branch",
        type: "wand",
        image: `${pathToWeaponImages}/wands/Suicide_Branch.webp`,
        properties: [],
    },
    {
        name: "Torch of Iro",
        type: "wand",
        image: `${pathToWeaponImages}/wands/Torch_of_Iro.webp`,
        properties: [],
    },
    {
        name: "Ume's Lament",
        type: "wand",
        image: `${pathToWeaponImages}/wands/Ume's_Lament.webp`,
        properties: [],
    },
];

export default uniques;